import { GradeCurriculum } from '../../../types';

export const grade7Curriculum: GradeCurriculum = {
  grade: 7,
  label: "7th Grade Mathematics",
  topics: [
    // ─── Strand 1: Rational Numbers (TEKS 7.2) ───────────────────────────
    {
      id: "7.ns.1",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 1, note: "Types of Numbers and the Number Line" },
      ],
      tpiCode: "7.2A",
      name: "Representations of Rational Numbers",
      description:
        "Extend representations of numbers to include negative fractions and decimals. Locate rational numbers on a number line and understand that every rational number can be expressed as a fraction, decimal, or percent.",
      gradeLevel: 7,
      strand: "Number & Operations",
      difficulty: 1,
      prerequisites: ["6.ns.1", "6.ns.3"],
      sampleProblems: [
        "Place -2.75, 1/3, and -4/5 on a number line. Order them from least to greatest.",
        "Express -7/8 as a decimal and as a percent.",
        "Which is greater: -3/4 or -0.8? Justify your answer using a number line.",
      ],
      isVerifiable: true,
      order: 1,
      nineWeeks: 1,
    },
    {
      id: "7.ns.2",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 1, note: "Types of Numbers and the Number Line" },
      ],
      tpiCode: "7.2A",
      name: "Comparing and Ordering Rational Numbers",
      description:
        "Compare and order rational numbers in various forms (fractions, decimals, percents) including negative values. Use inequality symbols and justify comparisons with common denominators or equivalent forms.",
      gradeLevel: 7,
      strand: "Number & Operations",
      difficulty: 1,
      prerequisites: ["6.ns.1", "7.ns.1"],
      sampleProblems: [
        "Order the following from least to greatest: 3/5, -0.75, 60%, -2/3, 0.4.",
        "Insert <, >, or = to make the statement true: -5/6 ___ -7/9.",
      ],
      isVerifiable: true,
      order: 2,
      nineWeeks: 1,
    },
    {
      id: "7.ns.3",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 19, note: "Percent" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 6, note: "Fraction Basics" },
      ],
      tpiCode: "7.2B",
      name: "Converting Between Fractions, Decimals, and Percents",
      description:
        "Fluently convert between fractions, decimals, and percents, including repeating decimals. Recognize common benchmark equivalences and apply conversions in context.",
      gradeLevel: 7,
      strand: "Number & Operations",
      difficulty: 1,
      prerequisites: ["6.ns.1", "6.ns.3"],
      sampleProblems: [
        "Convert 5/11 to a decimal. Is it terminating or repeating?",
        "A store advertises 3/8 off the original price. What percent discount is this?",
        "Express 0.0625 as a fraction in simplest form and as a percent.",
      ],
      isVerifiable: true,
      order: 3,
      nineWeeks: 1,
    },
    {
      id: "7.ns.4",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [11, 12], note: "Adding and Subtracting Positive and Negative Numbers" },
      ],
      tpiCode: "7.3A",
      name: "Adding and Subtracting Rational Numbers",
      description:
        "Add and subtract rational numbers including negative fractions and decimals. Understand addition of a negative number as moving left on the number line and apply properties of operations.",
      gradeLevel: 7,
      strand: "Number & Operations",
      difficulty: 2,
      prerequisites: ["6.ns.2", "7.ns.1"],
      sampleProblems: [
        "Evaluate: -3/4 + 5/6.",
        "A diver is at -12.5 meters and ascends 8.3 meters. What is the diver's new depth?",
        "Find the sum: -2 1/3 + (-4 2/5).",
      ],
      isVerifiable: true,
      order: 4,
      nineWeeks: 1,
    },
    {
      id: "7.ns.5",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 13, note: "Multiplying and Dividing Positive and Negative Numbers" },
      ],
      tpiCode: "7.3A",
      name: "Multiplying and Dividing Rational Numbers",
      description:
        "Multiply and divide rational numbers including negative fractions and mixed numbers. Apply rules for the sign of a product or quotient and connect to real-world contexts such as rate of change.",
      gradeLevel: 7,
      strand: "Number & Operations",
      difficulty: 2,
      prerequisites: ["6.ns.2", "7.ns.4"],
      sampleProblems: [
        "Evaluate: (-3/5) x (10/9).",
        "Divide: -4.8 / 1.2.",
        "The temperature drops 2.5 degrees per hour for 6 hours. Write a multiplication expression and find the total change.",
      ],
      isVerifiable: true,
      order: 5,
      nineWeeks: 1,
    },

    // ─── Strand 2: Expressions & Equations (TEKS 7.3) ────────────────────
    {
      id: "7.ee.1",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 29, note: "Like Terms" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 27, note: "Expressions" },
      ],
      tpiCode: "7.3B",
      name: "Simplifying Expressions and Combining Like Terms",
      description:
        "Simplify algebraic expressions by combining like terms. Identify coefficients, constants, and like terms in expressions with rational number coefficients.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 1,
      prerequisites: ["6.ee.1", "6.ee.2"],
      sampleProblems: [
        "Simplify: 3x + 7 - 5x + 2.",
        "Combine like terms: 2.5a - 4b + 1.3a + 6b.",
        "Identify the coefficient, variable, and constant in the expression 8m - 3.",
      ],
      isVerifiable: true,
      order: 6,
      nineWeeks: 2,
    },
    {
      id: "7.ee.2",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 28, note: "Properties (Distributive Property)" },
      ],
      tpiCode: "7.3C",
      name: "Distributive Property",
      description:
        "Apply the distributive property to expand and factor linear expressions with rational coefficients. Use the property to rewrite expressions in equivalent forms.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["6.ee.1", "7.ee.1"],
      sampleProblems: [
        "Expand: -2(3x - 5).",
        "Use the distributive property to write an equivalent expression for 4(2y + 3) - 5y.",
        "Factor: 12x + 18 using the GCF.",
      ],
      isVerifiable: true,
      order: 7,
      nineWeeks: 2,
    },
    {
      id: "7.ee.3",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 36, note: "Solving for Variables" },
      ],
      tpiCode: "7.3B",
      name: "Solving Two-Step Equations",
      description:
        "Solve two-step linear equations of the form ax + b = c where a, b, and c are rational numbers. Use inverse operations and verify solutions by substitution.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["6.ee.3", "7.ee.1", "7.ns.4"],
      sampleProblems: [
        "Solve for x: 3x + 7 = -8.",
        "Solve: (n / 4) - 2.5 = 6.",
        "Solve and check: -2p + 9 = 1.",
      ],
      isVerifiable: true,
      order: 8,
      nineWeeks: 2,
    },
    {
      id: "7.ee.4",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 39, note: "Word Problems with Equations and Inequalities" },
      ],
      tpiCode: "7.3A",
      name: "Writing Equations from Word Problems",
      description:
        "Translate real-world situations into two-step equations. Identify the unknown, define a variable, set up the equation, solve, and interpret the solution in context.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 3,
      prerequisites: ["6.ee.3", "7.ee.3"],
      sampleProblems: [
        "Maria has $45. She earns $8.50 per hour babysitting. How many hours must she work to have at least $130? Write and solve an equation.",
        "The perimeter of a rectangle is 56 cm. The length is 5 cm more than the width. Write an equation and find the dimensions.",
      ],
      isVerifiable: true,
      order: 9,
      nineWeeks: 2,
    },

    // ─── Strand 3: Inequalities (TEKS 7.4) ───────────────────────────────
    {
      id: "7.iq.1",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 38, note: "Solving and Graphing Inequalities" },
      ],
      tpiCode: "7.4A",
      name: "Writing and Graphing Inequalities",
      description:
        "Write one-variable inequalities to represent constraints or conditions in real-world and mathematical problems. Graph solution sets on a number line using open and closed circles.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 1,
      prerequisites: ["6.ee.3", "7.ee.1"],
      sampleProblems: [
        "Write an inequality for: 'You must be at least 48 inches tall to ride the roller coaster.' Graph the solution on a number line.",
        "Graph the inequality x > -3 on a number line. Is -3 included in the solution set?",
        "A parking garage charges a $5 flat fee plus $2 per hour. You have no more than $19. Write an inequality for the number of hours you can park.",
      ],
      isVerifiable: true,
      order: 10,
      nineWeeks: 2,
    },
    {
      id: "7.iq.2",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 38, note: "Solving and Graphing Inequalities" },
      ],
      tpiCode: "7.4A",
      name: "Solving One-Step and Two-Step Inequalities",
      description:
        "Solve one-step and two-step inequalities with rational number coefficients. Understand that multiplying or dividing both sides by a negative number reverses the inequality sign.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.iq.1", "7.ee.3"],
      sampleProblems: [
        "Solve and graph: -4x > 20.",
        "Solve: 2x - 7 <= 15. Graph the solution set.",
        "Solve: (m / -3) + 5 >= 8. Explain why the inequality symbol changes direction.",
      ],
      isVerifiable: true,
      order: 11,
      nineWeeks: 2,
    },

    // ─── Strand 4: Proportional Relationships (TEKS 7.4-7.5) ─────────────
    {
      id: "7.pr.1",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [16, 17], note: "Unit Rate, Unit Price, and Proportions" },
      ],
      tpiCode: "7.4B",
      name: "Constant of Proportionality and Unit Rates",
      description:
        "Identify the constant of proportionality (unit rate) in tables, graphs, equations, and verbal descriptions. Compute unit rates with complex fractions (e.g., 1/2 mile per 1/4 hour).",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 1,
      prerequisites: ["6.rp.1", "6.rp.2"],
      sampleProblems: [
        "A recipe uses 2/3 cup of sugar for every 1/2 batch. What is the unit rate of sugar per batch?",
        "The table shows that 3 pounds of apples cost $5.25 and 7 pounds cost $12.25. Is this a proportional relationship? If so, find the constant of proportionality.",
        "Identify the constant of proportionality in the equation y = 4.5x.",
      ],
      isVerifiable: true,
      order: 12,
      nineWeeks: 3,
    },
    {
      id: "7.pr.2",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 17, note: "Proportions" },
      ],
      tpiCode: "7.4C",
      name: "Proportional vs. Non-Proportional Relationships",
      description:
        "Distinguish between proportional and non-proportional linear relationships using tables, graphs, and equations. Recognize that proportional graphs pass through the origin and have a constant ratio y/x.",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 2,
      prerequisites: ["6.rp.1", "7.pr.1"],
      sampleProblems: [
        "Does the table represent a proportional relationship? x: 2, 4, 6; y: 5, 10, 15. Explain.",
        "A gym charges a $25 sign-up fee plus $30 per month. Is the total cost proportional to the number of months? Explain using a graph or table.",
      ],
      isVerifiable: true,
      order: 13,
      nineWeeks: 3,
    },
    {
      id: "7.pr.3",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 25, note: "Percent Rate of Change" },
      ],
      tpiCode: "7.4D",
      name: "Percent Increase and Decrease",
      description:
        "Calculate percent increase and percent decrease. Apply the percent change formula and solve real-world problems involving growth and reduction.",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 2,
      prerequisites: ["6.rp.3", "7.ns.3"],
      sampleProblems: [
        "A shirt originally costs $40 and is now $52. What is the percent increase?",
        "A town's population decreased from 12,000 to 10,200. Find the percent decrease.",
        "An item's price increased by 15% to $69. What was the original price?",
      ],
      isVerifiable: true,
      order: 14,
      nineWeeks: 3,
    },
    {
      id: "7.pr.4",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [21, 23], note: "Taxes/Fees, Discounts/Markups, Gratuity/Commission" },
      ],
      tpiCode: "7.4E",
      name: "Markup, Markdown, Tax, Tip, and Commission",
      description:
        "Solve real-world problems involving markup, markdown (discount), sales tax, tips, and commission. Calculate the final price or the original price when given a percent adjustment.",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 2,
      prerequisites: ["6.rp.3", "7.pr.3"],
      sampleProblems: [
        "A store buys a jacket for $35 and marks it up 60%. What is the selling price?",
        "A meal costs $28.50. If the sales tax is 8.25% and you leave a 20% tip on the pre-tax amount, what is the total cost?",
        "A realtor earns a 3% commission on home sales. How much does she earn on a $275,000 home?",
      ],
      isVerifiable: true,
      order: 15,
      nineWeeks: 3,
    },
    {
      id: "7.pr.5",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 24, note: "Simple Interest" },
      ],
      tpiCode: "7.4F",
      name: "Simple Interest",
      description:
        "Use the simple interest formula I = Prt to solve problems involving savings accounts, loans, and investments. Calculate interest, total amount, principal, rate, or time.",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 3,
      prerequisites: ["7.pr.3", "7.ee.3"],
      sampleProblems: [
        "You deposit $1,200 in a savings account that earns 3.5% simple interest per year. How much interest do you earn in 4 years?",
        "A loan of $5,000 accrues $750 in simple interest over 3 years. What is the annual interest rate?",
      ],
      isVerifiable: true,
      order: 16,
      nineWeeks: 3,
    },

    // ─── Strand 5: Linear Relationships (TEKS 7.7) ───────────────────────
    {
      id: "7.lr.1",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
      tpiCode: "7.7A",
      name: "Representing Linear Relationships",
      description:
        "Represent linear relationships using tables, graphs, equations, and verbal descriptions. Generate a table of values from an equation, plot ordered pairs, and connect representations.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["6.ee.2", "7.pr.1"],
      sampleProblems: [
        "Complete the table for y = 2x - 3 using x-values -2, 0, 1, 4. Then graph the ordered pairs.",
        "A plumber charges $50 for a house call plus $35 per hour. Write an equation, make a table for 0 to 5 hours, and describe the graph.",
        "From the graph of a line passing through (0, 4) and (3, 10), write the equation of the line.",
      ],
      isVerifiable: true,
      order: 17,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "7.lr.2",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 57, note: "Slope" },
      ],
      tpiCode: "7.7A",
      name: "Slope and Rate of Change",
      description:
        "Understand slope as the rate of change (rise over run) of a linear relationship. Calculate slope from two points, a table, or a graph and interpret its meaning in context.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.pr.1", "7.lr.1"],
      sampleProblems: [
        "Find the slope of the line passing through (-1, 3) and (2, -6).",
        "A candle is 12 inches tall and burns at a rate of 0.5 inches per hour. What is the slope? What does it represent?",
        "From a table: x: 1, 3, 5; y: 8, 14, 20. Find the rate of change.",
      ],
      isVerifiable: true,
      order: 18,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "7.lr.3",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
      tpiCode: "7.7A",
      name: "Y-Intercept and Direct Variation",
      description:
        "Identify the y-intercept of a linear relationship from a graph, table, or equation. Recognize direct variation (y = kx) as a special linear relationship where the y-intercept is 0.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.lr.1", "7.lr.2", "7.pr.2"],
      sampleProblems: [
        "Identify the slope and y-intercept of y = -3x + 7. What does the y-intercept represent if this models a bank balance over time?",
        "Does y = 4x represent direct variation? Explain. What is the constant of variation?",
        "A graph passes through (0, 0) and (5, 15). Is this a direct variation? Write the equation.",
      ],
      isVerifiable: true,
      order: 19,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },

    // ─── Strand 6: Proportional Geometry (TEKS 7.5) ──────────────────────
    {
      id: "7.pg.1",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 50, note: "Similar Figures and Scale Drawings" },
      ],
      tpiCode: "7.5A",
      name: "Scale Drawings and Scale Factors",
      description:
        "Use scale factors to solve problems involving scale drawings and maps. Determine actual distances from a scale drawing and create scale drawings given dimensions and a scale.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["6.rp.1", "6.rp.2", "7.pr.1"],
      sampleProblems: [
        "On a map, 1 inch represents 25 miles. Two cities are 3.5 inches apart on the map. What is the actual distance?",
        "A blueprint has a scale of 1 cm : 2.5 m. A room measures 6 cm by 4.8 cm on the blueprint. What are the actual dimensions?",
        "An architect creates a drawing with a scale factor of 1:50. If a wall is actually 15 meters long, how long is it on the drawing?",
      ],
      isVerifiable: true,
      order: 20,
      nineWeeks: 4,
    },
    {
      id: "7.pg.2",
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 50, note: "Similar Figures and Scale Drawings" },
      ],
      tpiCode: "7.5B",
      name: "Similar Figures and Proportional Reasoning",
      description:
        "Identify similar figures and use proportions to find missing side lengths. Understand that corresponding angles are congruent and corresponding sides are proportional in similar figures.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["6.rp.2", "7.pg.1", "7.pr.1"],
      sampleProblems: [
        "Triangle ABC is similar to triangle DEF. If AB = 6, BC = 8, DE = 9, find EF.",
        "A flagpole casts a shadow 12 feet long. A 5-foot person standing nearby casts a 3-foot shadow. How tall is the flagpole?",
        "Two rectangles are similar. The first is 4 cm by 6 cm. The second has a width of 10 cm. Find its length.",
      ],
      isVerifiable: true,
      order: 21,
      nineWeeks: 4,
    },

    // =====================================================================
    // SECOND-HALF TOPICS (migrated from grade-8-accel-prep + new gap topics)
    // =====================================================================

    // ─── Strand 2 (cont): Equations & Inequalities Extensions (TEKS 7.10/7.11) ───
    {
      id: "7.ee.5",
      tpiCode: "7.10B",
      name: "Representing Solutions on Number Lines",
      description:
        "Graph solutions to equations and inequalities on a number line. Understand the difference between a single-point solution (equation) and a range of solutions (inequality). Use open vs closed circles for strict vs inclusive inequalities.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 1,
      prerequisites: ["7.ee.3", "7.iq.1"],
      sampleProblems: [
        "Solve 3x - 5 = 10 and plot the solution on a number line.",
        "Explain the difference between graphing x = 4 and x > 4 on a number line.",
        "Graph x <= -2 on a number line. Should the circle be open or closed? Why?",
        "Graph x > 3 on a number line. Explain why an open circle is used.",
      ],
      isVerifiable: true,
      order: 22,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'number-line',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 38,
          unit: "Algebra: Equations and Inequalities",
          note: "Graphing solutions on number lines",
        },
      ],
    },
    {
      id: "7.ee.6",
      tpiCode: "7.10C",
      name: "Writing Real-World Problems from Equations",
      description:
        "Given a two-step equation, write a corresponding real-world problem. Interpret the variable, coefficients, and constants in context. Connect mathematical representations to real situations.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.ee.3", "7.ee.4"],
      sampleProblems: [
        "Write a real-world problem that could be modeled by 5x + 2 = 37.",
        "Write a word problem for the equation 3x - 7 = 20.",
        "The equation 8.50x + 45 = 130 represents Maria's earnings. What could x, 8.50, 45, and 130 represent?",
        "Write a real-world scenario for the inequality 3x + 14 <= 50.",
      ],
      isVerifiable: false,
      order: 23,
      nineWeeks: 3,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 39,
          unit: "Algebra: Equations",
          note: "Writing equations from contexts (reverse direction)",
        },
      ],
    },
    {
      id: "7.ee.7",
      tpiCode: "7.11B",
      name: "Verifying Solutions to Equations and Inequalities",
      description:
        "Substitute given values into equations and inequalities to determine if they are solutions. Test multiple values and explain why each does or does not satisfy the equation or inequality.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 1,
      prerequisites: ["7.ee.3", "7.iq.2"],
      sampleProblems: [
        "Is x = 5 a solution to 3x + 7 = 22? Show your work.",
        "Which value makes 2x - 4 = 10 true: x = 3, x = 7, or x = 5?",
        "Does x = -3 satisfy the inequality 2x + 1 > -4? Explain.",
        "Test x = 2 and x = 6 in the equation 4x - 3 = 21. Which is the solution?",
      ],
      isVerifiable: true,
      order: 24,
      nineWeeks: 3,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 36,
          unit: "Algebra: Equations and Inequalities",
          note: "Checking solutions by substitution",
        },
      ],
    },

    // ─── Strand 4 (cont): Proportional Relationships Extensions (TEKS 7.4) ───
    {
      id: "7.pr.6",
      tpiCode: "7.4D",
      name: "Multi-Step Problems with Ratios, Rates, and Percents",
      description:
        "Solve multi-step problems involving ratios, rates, and percents. Set up and solve proportions using cross-multiplication. Apply to tax, tip, discount, markup, and commission problems in combination.",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 3,
      prerequisites: ["7.pr.3", "7.pr.4"],
      sampleProblems: [
        "Solve: 3/8 = x/20.",
        "A meal costs $45. Tax is 8.25% and you leave a 20% tip (on the pre-tax amount). What is the total?",
        "A jacket is marked up 40% from a wholesale cost of $35. What is the retail price?",
        "A salesperson earns 6% commission. How much must they sell to earn $1,500?",
      ],
      isVerifiable: true,
      order: 25,
      nineWeeks: 3,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapters: [15, 26],
          unit: "Ratios, Proportions, and Percents",
          note: "Combined ratio/rate/percent applications",
        },
      ],
    },
    {
      id: "7.pr.7",
      tpiCode: "7.4E",
      name: "Converting Between Measurement Systems",
      description:
        "Use proportions to convert between customary and metric measurement systems. Apply common conversion factors (e.g., 1 inch = 2.54 cm, 1 mile = 1.609 km, 1 gallon = 3.785 liters).",
      gradeLevel: 7,
      strand: "Ratios & Proportional Relationships",
      difficulty: 1,
      prerequisites: ["7.pr.1"],
      sampleProblems: [
        "Convert 15 inches to centimeters using 1 inch = 2.54 cm.",
        "A recipe calls for 2 liters of water. How many cups is that? (1 liter = 4.227 cups)",
        "A race is 10 kilometers. How many miles is that? (1 mile = 1.609 km)",
        "A room is 12 feet long. What is the length in meters? (1 foot = 0.3048 m)",
      ],
      isVerifiable: true,
      order: 26,
      nineWeeks: 3,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 18,
          unit: "Ratios, Proportions, and Percents",
          note: "Customary/metric conversions via proportions",
        },
      ],
    },

    // ─── Strand 5 (cont): Linear Relationships in y = mx + b (TEKS 7.7) ────
    {
      id: "7.lr.4",
      tpiCode: "7.7A",
      name: "Linear Relationships (y = mx + b)",
      description:
        "Represent linear relationships using tables, graphs, equations, and verbal descriptions. Identify the rate of change (slope, m) and starting value (y-intercept, b) from each representation. The starting value is the output when the input is zero. Calculate rate of change from a graph by dividing vertical distance by horizontal distance.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.lr.1", "7.lr.2", "7.lr.3"],
      sampleProblems: [
        "For y = 2x + 5, what is the starting value? Verify by substituting x = 0.",
        "Match each equation with its starting value: y = 5x + 6, y = 4x - 12, y = x + 7.",
        "From a graph, find the rate of change by dividing the vertical distance between two points by the horizontal distance.",
        "A plumber charges $50 plus $35/hour. Write the equation, make a table for 0-4 hours, and identify the rate of change and starting value.",
      ],
      isVerifiable: true,
      order: 27,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 58,
          unit: "Coordinate Plane and Functions",
          note: "Linear equations in slope-intercept form",
        },
      ],
    },
    {
      id: "7.lr.5",
      tpiCode: "7.7A",
      name: "Writing Equations of Linear Relationships",
      description:
        "Write equations of linear relationships in slope-intercept form (y = mx + b) from verbal descriptions, tables, and graphs. Identify m and b, then substitute into y = mx + b. Use the equation to make predictions.",
      gradeLevel: 7,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.lr.4"],
      sampleProblems: [
        "Shandra deposited $100 and adds $20/week. Write the equation. How much after 8 weeks?",
        "From the table (x: -2, 0, 4, 10; y: 2, 3, 5, 8), find the rate of change and starting value. Write the equation.",
        "Find and describe the rate of change and starting value: A temperature starts at 68 degrees F and drops 3 degrees per hour.",
        "A candle is 12 inches tall and burns 0.5 inches per hour. Write the equation. When will it be 3 inches?",
      ],
      isVerifiable: true,
      order: 28,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 58,
          unit: "Coordinate Plane and Functions",
          note: "Writing linear equations from tables, graphs, and contexts",
        },
      ],
    },

    // ─── Strand 6 (cont): Proportional Geometry Extensions (TEKS 7.5) ──────
    {
      id: "7.pg.3",
      tpiCode: "7.5A",
      name: "Critical Attributes of Similarity",
      description:
        "Identify similar and congruent figures. In similar figures, corresponding angles are equal and corresponding sides are proportional. Congruent figures are the same shape AND size. Similar figures are the same shape but may differ in size. Identify corresponding angles and sides.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 1,
      prerequisites: ["7.pg.2"],
      sampleProblems: [
        "Quadrilateral ABCD ~ Quadrilateral WXYZ. List all pairs of corresponding angles and sides.",
        "True or false: Congruent figures are always similar, but similar figures are not always congruent. Explain.",
        "Two triangles have the same angle measures (40, 60, 80 degrees) but different side lengths. Are they similar, congruent, or neither?",
        "If Triangle PQR ~ Triangle XYZ, and angle P = 55 degrees and angle Q = 70 degrees, what is angle Z?",
      ],
      isVerifiable: true,
      order: 29,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 50,
          unit: "Geometry",
          note: "Similar figures and scale drawings",
        },
      ],
    },
    {
      id: "7.pg.4",
      tpiCode: "7.5C",
      name: "Solving Problems with Similar Shapes",
      description:
        "Use proportions to find missing side lengths in similar figures. Write ratios of corresponding sides, set up proportions, and solve using cross-multiplication.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.pg.2", "7.pg.3"],
      sampleProblems: [
        "Triangle PQR ~ Triangle VWX. PQ = 21, VW = 33, QR = 7. Find WX using a proportion.",
        "Triangle ABC ~ Triangle DEF. AB = 6, BC = 8, DE = 9. Find EF.",
        "Two similar rectangles: the first is 4 cm by 6 cm. The second has width 10 cm. Find its length.",
        "A flagpole casts a 12-foot shadow. A 5-foot person nearby casts a 3-foot shadow. How tall is the flagpole?",
      ],
      isVerifiable: true,
      order: 30,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 50,
          unit: "Geometry",
          note: "Similar figures and scale drawings",
        },
      ],
    },
    {
      id: "7.pg.5",
      tpiCode: "7.5C",
      name: "Scale Drawings",
      description:
        "Create and interpret scale drawings. Determine scale factors from blueprints and maps. Write and solve proportions to find actual or drawing dimensions. Understand that a scale factor is the ratio of drawing size to actual size.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.pg.1", "7.pg.4"],
      sampleProblems: [
        "An architect uses a scale of 2 inches = 30 feet. The actual stadium is 180 feet tall. How tall is it in the blueprint?",
        "A blueprint has a scale of 1 cm : 2.5 m. A room is 6 cm by 4.8 cm on the blueprint. What are the actual dimensions?",
        "On a map, 1 inch = 25 miles. Two cities are 3.5 inches apart. What is the actual distance?",
        "On a map, 1.5 inches represents 50 miles. Two cities are 4.5 inches apart. What is the actual distance?",
      ],
      isVerifiable: true,
      order: 31,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 50,
          unit: "Geometry",
          note: "Scale drawings and scale factors",
        },
      ],
    },

    // ─── Strand 7: Circles & 2D Geometry (TEKS 7.5B, 7.9B, 7.9C) ───────────
    {
      id: "7.cg.1",
      tpiCode: "7.5B",
      name: "Pi and Circle Relationships",
      description:
        "Understand that pi is the ratio of circumference to diameter for every circle. Approximate pi by measuring and dividing. Use pi to find circumference when diameter is known and vice versa.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 1,
      prerequisites: ["7.pr.1"],
      sampleProblems: [
        "Measure the circumference and diameter of three circular objects. Divide circumference by diameter for each. What do you notice?",
        "If a circle has circumference 31.4 cm, what is its diameter? Use pi = 3.14.",
        "Explain why pi is approximately 3.14 using the definition of pi as a ratio.",
        "A circular garden has a diameter of 18 feet. How much fencing is needed to go around it?",
      ],
      isVerifiable: true,
      order: 32,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 45,
          unit: "Geometry",
          note: "Circles: pi, circumference, area",
        },
      ],
    },
    {
      id: "7.cg.2",
      tpiCode: "7.9B",
      name: "Circumference and Area of Circles",
      description:
        "Find the circumference using C = pi*d or C = 2*pi*r. Find the area using A = pi*r^2. Understand pi as the ratio of circumference to diameter (approximately 3.14). Convert between radius and diameter. Apply to real-world problems.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.cg.1"],
      sampleProblems: [
        "A circle measures 10 mm across through the center. Find its area using pi = 3.14. First find the radius.",
        "Match each word to its description: circumference, radius, diameter, pi.",
        "A circular fishpond has a diameter of 8 feet. Henry is lining the bottom with stones. How much area do the stones need to cover?",
        "A pizza has a diameter of 14 inches. What is the area of one slice if cut into 8 equal slices?",
      ],
      isVerifiable: true,
      order: 33,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 45,
          unit: "Geometry",
          note: "Circumference and area of circles",
        },
      ],
    },
    {
      id: "7.cg.3",
      tpiCode: "7.9C",
      name: "Composite Figures (Area and Perimeter)",
      description:
        "Find the area and perimeter of composite figures made up of rectangles, triangles, parallelograms, trapezoids, and semicircles. Decompose complex shapes into simpler ones, calculate each piece, then add or subtract appropriately.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.cg.2"],
      sampleProblems: [
        "Find the area of an L-shaped figure with dimensions 10 cm x 4 cm with a 3 cm x 3 cm square cut from the corner.",
        "A figure is made of a rectangle (8 m x 5 m) with a semicircle on one short side. Find the total area.",
        "Find the area of a trapezoid with bases 10 in and 6 in, and height 4 in.",
        "A swimming pool is shaped like a rectangle with semicircles on both ends. The rectangle is 25 m x 10 m. Find the total area.",
      ],
      isVerifiable: true,
      order: 34,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 45,
          unit: "Geometry",
          note: "Composite area and perimeter problems",
        },
      ],
    },

    // ─── Strand 8: Angle Relationships (TEKS 7.11C) ────────────────────────
    {
      id: "7.cg.4",
      tpiCode: "7.11C",
      name: "Angle Pair Relationships (Complementary, Supplementary, Vertical, Adjacent)",
      description:
        "Identify and apply the relationships between complementary angles (sum 90 degrees), supplementary angles (sum 180 degrees), vertical angles (equal), and adjacent angles. Write and solve equations to find unknown angle measures using these relationships.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.ee.3"],
      sampleProblems: [
        "Two angles are complementary. One measures 37 degrees. What is the measure of the other?",
        "Angles A and B are supplementary. If angle A = (3x + 10) degrees and angle B = (2x + 20) degrees, find x and both angle measures.",
        "Two lines intersect, forming four angles. One angle measures 65 degrees. Find the measures of the other three angles using vertical and supplementary angle relationships.",
        "Angles 1 and 2 are adjacent and together form a straight angle. If angle 1 is 4 times angle 2, find both angles.",
      ],
      isVerifiable: true,
      order: 35,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 41,
          unit: "Geometry",
          note: "Angle pair relationships",
        },
      ],
    },
    {
      id: "7.cg.5",
      tpiCode: "7.11C",
      name: "Triangle Angle Sum Relationships",
      description:
        "Apply the triangle angle sum theorem (interior angles sum to 180 degrees). Find missing angles in triangles. Write and solve equations to find unknown angle measures labeled with variables or expressions. Use the exterior angle theorem when appropriate.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.cg.4"],
      sampleProblems: [
        "A triangle has angles measuring 45 degrees and 72 degrees. Find the third angle.",
        "In a triangle, one angle is twice the smallest and the third is 20 degrees more than the smallest. Find all three angles.",
        "An exterior angle of a triangle measures 130 degrees. One non-adjacent interior angle is 55 degrees. Find the other.",
        "Two angles of a triangle are (2x + 10) and (3x - 5) and the third is 55. Find x and all angle measures.",
      ],
      isVerifiable: true,
      order: 36,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 41,
          unit: "Geometry",
          note: "Triangle angle sum theorem",
        },
      ],
    },

    // ─── Strand 9: Volume & Surface Area (TEKS 7.9A, 7.9D) ─────────────────
    {
      id: "7.vl.1",
      tpiCode: "7.9A",
      name: "Volume of Prisms",
      description:
        "Find the volume of rectangular and triangular prisms using V = Bh where B is the area of the base. Apply to real-world problems including capacity and packaging.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.cg.3"],
      sampleProblems: [
        "Find the volume of a rectangular prism with length 8 cm, width 5 cm, and height 3 cm.",
        "A triangular prism has a base triangle with base 6 m and height 4 m. The prism is 10 m long. Find the volume.",
        "A fish tank is 24 in long, 12 in wide, and 16 in tall. How many cubic inches of water does it hold when full?",
        "A box has a volume of 240 cubic cm. If the base is 8 cm by 5 cm, what is the height?",
      ],
      isVerifiable: true,
      order: 37,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 47,
          unit: "Geometry",
          note: "Volume of prisms",
        },
      ],
    },
    {
      id: "7.vl.2",
      tpiCode: "7.9A",
      name: "Volume of Pyramids",
      description:
        "Find the volume of pyramids with rectangular and triangular bases using V = (1/3)Bh. Compare volumes of pyramids and prisms with the same base and height.",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 3,
      prerequisites: ["7.vl.1"],
      sampleProblems: [
        "Find the volume of a pyramid with a square base of side 6 cm and height 10 cm.",
        "A pyramid has a rectangular base 8 m x 5 m and a height of 12 m. What is its volume?",
        "A pyramid and a prism have the same square base (side 4 in) and the same height (9 in). How do their volumes compare?",
        "The Great Pyramid has a square base of about 230 m and a height of about 146 m. Estimate its volume.",
      ],
      isVerifiable: true,
      order: 38,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 47,
          unit: "Geometry",
          note: "Volume of pyramids",
        },
      ],
    },
    {
      id: "7.vl.3",
      tpiCode: "7.9D",
      name: "Surface Area via Nets",
      description:
        "Find the lateral and total surface area of rectangular prisms and triangular prisms by unfolding them into nets. Identify all the faces of a 3D figure, calculate the area of each face, and sum them. Distinguish lateral surface area (sides only) from total surface area (all faces).",
      gradeLevel: 7,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.cg.3", "7.vl.1"],
      sampleProblems: [
        "Draw the net of a rectangular prism with dimensions 5 cm x 3 cm x 2 cm. Use the net to find the total surface area.",
        "A triangular prism has a base triangle with legs 3 in and 4 in (hypotenuse 5 in). The prism is 10 in long. Use the net to find lateral and total surface area.",
        "A box (rectangular prism) is 12 in x 8 in x 5 in. How much wrapping paper is needed to cover it (total surface area)?",
        "Find the lateral surface area of a rectangular prism with a 4 m x 6 m base and a height of 9 m. (Lateral area = perimeter of base x height.)",
      ],
      isVerifiable: true,
      order: 39,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 48,
          unit: "Geometry",
          note: "Surface area and nets of 3D figures",
        },
      ],
    },

    // ─── Strand 10: Statistics & Sampling (TEKS 7.12) ──────────────────────
    {
      id: "7.st.1",
      tpiCode: "7.12B",
      name: "Box Plots and Dot Plots",
      description:
        "Construct and interpret box plots (box-and-whisker plots) and dot plots from a numeric data set. Identify the five-number summary (minimum, Q1, median, Q3, maximum), the interquartile range (IQR), and any outliers. Compare distributions visually.",
      gradeLevel: 7,
      strand: "Data & Statistics",
      difficulty: 2,
      prerequisites: [],
      sampleProblems: [
        "From the data set 5, 8, 10, 12, 15, 18, 20, 22, 25, find the five-number summary and construct a box plot.",
        "Construct a dot plot from the quiz scores: 7, 8, 8, 9, 9, 9, 10, 10, 7, 8. What is the mode?",
        "A box plot has Q1 = 12, median = 18, Q3 = 25, minimum = 8, maximum = 32. What is the IQR? What does the IQR represent?",
        "Compare two box plots: Class A (median 75, IQR 15) and Class B (median 80, IQR 25). Which class scored higher on average? Which had more variability?",
      ],
      isVerifiable: true,
      order: 40,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'data-display',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 53,
          unit: "Statistics",
          note: "Box plots, dot plots, and the five-number summary",
        },
      ],
    },
    {
      id: "7.st.2",
      tpiCode: "7.12A",
      name: "Comparing Two Data Sets (Center and Spread)",
      description:
        "Compare two groups of numeric data using measures of center (mean, median) and measures of spread (range, interquartile range, mean absolute deviation). Use dot plots, box plots, and histograms to compare distributions and draw conclusions.",
      gradeLevel: 7,
      strand: "Data & Statistics",
      difficulty: 2,
      prerequisites: ["7.st.1"],
      sampleProblems: [
        "Find the mean, median, and range of: 12, 15, 18, 22, 18, 14, 20.",
        "Compare two data sets using their means and ranges. Which set is more spread out? Data A: 10, 12, 14, 16, 18. Data B: 5, 10, 14, 18, 23.",
        "Calculate the mean absolute deviation (MAD) of: 10, 12, 14, 16, 18.",
        "Two basketball teams' scoring data have the same mean (75 pts) but Team X has range 40 and Team Y has range 12. Which team is more consistent? Explain.",
      ],
      isVerifiable: true,
      order: 41,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'data-display',
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 52,
          unit: "Statistics",
          note: "Comparing data sets with center and spread",
        },
      ],
    },
    {
      id: "7.st.3",
      tpiCode: "7.12C",
      name: "Random Sampling and Inferences",
      description:
        "Understand the difference between a population and a sample. Recognize that random samples tend to be representative of a population while biased samples are not. Use data from a random sample to make inferences and predictions about the population.",
      gradeLevel: 7,
      strand: "Data & Statistics",
      difficulty: 2,
      prerequisites: ["7.st.1"],
      sampleProblems: [
        "Identify the population and the sample: A principal surveys 30 randomly chosen students out of 600 about lunch preferences. What is the population? What is the sample?",
        "Which sampling method is more likely to be representative? (a) Surveying only the basketball team about favorite sports. (b) Randomly selecting 50 students from the whole school. Explain.",
        "A random sample of 50 light bulbs out of 5,000 finds 3 defective. About how many defective bulbs would you expect in the full batch?",
        "A poll of 100 randomly chosen voters finds 62 favor a new park. Estimate how many of the town's 8,000 voters favor the park.",
      ],
      isVerifiable: true,
      order: 42,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 51,
          unit: "Statistics",
          note: "Random sampling and inferences about populations",
        },
      ],
    },

    // ─── Strand 11: Personal Financial Literacy (TEKS 7.13) ────────────────
    {
      id: "7.pf.1",
      tpiCode: "7.13B",
      name: "Personal Net Worth Statements",
      description:
        "Identify the components of a personal net worth statement, including assets (what you own) and liabilities (what you owe). Calculate net worth as the difference: net worth = total assets - total liabilities. Track how net worth changes over time.",
      gradeLevel: 7,
      strand: "Financial Literacy",
      difficulty: 2,
      prerequisites: ["7.ns.4"],
      sampleProblems: [
        "Jordan has $1,200 in savings, a bike worth $250, and a phone worth $400. He owes his parents $300 for the phone. Calculate his net worth.",
        "Maya's assets: car ($8,000), savings ($2,500), laptop ($600). Her liabilities: car loan ($4,200), credit card ($350). What is her net worth?",
        "A person has total assets of $24,500 and a net worth of $18,200. What are their total liabilities?",
        "Last year Sam's net worth was $1,500. This year his assets grew by $800 and his liabilities grew by $200. What is his net worth now?",
      ],
      isVerifiable: true,
      order: 43,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 24,
          unit: "Ratios, Proportions, and Percents",
          note: "Financial literacy basics; assets, liabilities, and net worth",
        },
      ],
    },
    {
      id: "7.pf.2",
      tpiCode: "7.13C",
      name: "Credit History and Credit Reports",
      description:
        "Understand what credit history is and how it is recorded on a credit report. Identify factors that affect credit scores (payment history, amounts owed, length of credit history). Recognize the importance of building good credit over time.",
      gradeLevel: 7,
      strand: "Financial Literacy",
      difficulty: 1,
      prerequisites: [],
      sampleProblems: [
        "Explain what a credit report is and list three things it might include.",
        "Which of the following would most likely hurt a person's credit score: (a) paying bills on time, (b) missing several credit card payments, (c) keeping the same credit card for 10 years? Explain.",
        "A credit score ranges from 300 to 850. Score A is 580 and Score B is 740. Which person is more likely to be approved for a loan, and why?",
        "Why might a bank check a person's credit history before giving them a loan?",
      ],
      isVerifiable: false,
      order: 44,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 24,
          unit: "Ratios, Proportions, and Percents",
          note: "Financial literacy: credit history and credit reports",
        },
      ],
    },
    {
      id: "7.pf.3",
      tpiCode: "7.13D",
      name: "Debit Cards vs. Credit Cards",
      description:
        "Compare the features of debit cards and credit cards. Understand that debit cards withdraw money directly from a checking account, while credit cards borrow money from the issuer (often with interest charges if not paid in full). Identify advantages and disadvantages of each.",
      gradeLevel: 7,
      strand: "Financial Literacy",
      difficulty: 1,
      prerequisites: [],
      sampleProblems: [
        "List two advantages and two disadvantages of using a debit card vs. a credit card.",
        "Lila buys a $60 shirt. With a debit card, where does the money come from? With a credit card, where does it come from?",
        "A credit card balance of $400 has an annual interest rate of 18%. If only the minimum payment is made, how much interest accrues in one month? (Use simple interest for one month: I = Prt with t = 1/12.)",
        "Which is more likely to cause debt if used carelessly: a debit card or a credit card? Explain why.",
      ],
      isVerifiable: true,
      order: 45,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 24,
          unit: "Ratios, Proportions, and Percents",
          note: "Financial literacy: debit vs. credit cards",
        },
      ],
    },
    {
      id: "7.pf.4",
      tpiCode: "7.13E",
      name: "Financial Responsibility of Loans (Interest Over Time)",
      description:
        "Analyze the financial responsibility of borrowing money. Use the simple interest formula I = Prt to calculate the total cost of a loan over time. Understand that longer repayment periods or higher interest rates result in paying significantly more than the original loan amount.",
      gradeLevel: 7,
      strand: "Financial Literacy",
      difficulty: 3,
      prerequisites: ["7.pr.5"],
      sampleProblems: [
        "A car loan of $12,000 has a 6% simple interest rate for 5 years. How much interest will be paid? What is the total cost?",
        "Compare two loan options for $5,000: Option A is 8% simple interest for 3 years; Option B is 5% simple interest for 6 years. Which costs more in interest?",
        "A student takes out a $20,000 loan at 4.5% simple interest. If they take 10 years to repay, how much interest do they pay total?",
        "A loan totals $7,500 paid back over 3 years with $1,350 in simple interest. What was the annual interest rate?",
      ],
      isVerifiable: true,
      order: 46,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 24,
          unit: "Ratios, Proportions, and Percents",
          note: "Simple interest and loan costs over time",
        },
      ],
    },
    {
      id: "7.pf.5",
      tpiCode: "7.13F",
      name: "College Costs and Savings",
      description:
        "Estimate the costs of attending college, including tuition, fees, room and board, books, and other expenses. Develop savings plans using monthly or annual deposits. Use proportional reasoning and the simple interest formula to project savings growth.",
      gradeLevel: 7,
      strand: "Financial Literacy",
      difficulty: 3,
      prerequisites: ["7.pr.5", "7.pf.4"],
      sampleProblems: [
        "A college estimates total annual cost (tuition, room, board, books) at $28,000. What is the cost for a 4-year degree?",
        "A family saves $200 per month for college starting when their child is 5 years old. How much will they have saved by age 18 (ignoring interest)?",
        "A college savings account is opened with $5,000 at 4% simple interest. How much will be in the account after 12 years?",
        "If college costs are projected to be $35,000 per year in 10 years, how much must a family save each month for 10 years to fund 4 years of college? (Ignore interest.)",
      ],
      isVerifiable: true,
      order: 47,
      nineWeeks: 4,
      bookRefs: [
        {
          title: "Big Fat Middle School Math Workbook",
          isbn: "9781523513581",
          chapter: 24,
          unit: "Ratios, Proportions, and Percents",
          note: "College savings, simple interest, and planning",
        },
      ],
    },
  ],
};
