import { GradeCurriculum } from '../../../types';

export const grade8Curriculum: GradeCurriculum = {
  grade: 8,
  label: "8th Grade Mathematics",
  topics: [
    // ─── Strand 1: Real Number System (TEKS 8.2) ─────────────────────────
    {
      id: "8.rn.1",
      tpiCode: "8.2A",
      name: "Sets and Subsets of Real Numbers",
      description:
        "Extend previous knowledge of sets and subsets to include the real number system. Classify numbers as natural, whole, integer, rational, or irrational and represent the relationships among these subsets using a Venn diagram or set diagram.",
      gradeLevel: 8,
      strand: "Number & Operations",
      difficulty: 1,
      prerequisites: ["7.ns.1", "7.ns.3"],
      sampleProblems: [
        "Classify each number as natural, whole, integer, rational, irrational, and/or real: -7, 0, sqrt(2), 3/4, pi, 5.",
        "Draw a Venn diagram showing the relationships among natural numbers, whole numbers, integers, rationals, and irrationals. Place sqrt(9), -3, 0.5, and sqrt(7) in the correct regions.",
        "True or false: every integer is a rational number. Justify your answer.",
      ],
      isVerifiable: true,
      order: 1,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 1, note: "Types of Numbers" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 34, note: "Square and Cube Roots" },
      ],
    },
    {
      id: "8.rn.2",
      tpiCode: "8.2B",
      name: "Approximating and Locating Irrational Numbers",
      description:
        "Approximate the value of an irrational number, including pi and square roots of non-perfect squares, and locate it on a number line between two consecutive integers or rationals.",
      gradeLevel: 8,
      strand: "Number & Operations",
      difficulty: 2,
      prerequisites: ["8.rn.1", "7.ns.1"],
      sampleProblems: [
        "Between which two consecutive integers does sqrt(58) lie? Estimate sqrt(58) to the nearest tenth and locate it on a number line.",
        "Approximate sqrt(20) and place it on a number line with the points 4, 4.5, and 5 marked.",
        "Order pi, sqrt(10), and 3.2 on a number line from least to greatest.",
      ],
      isVerifiable: true,
      order: 2,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'number-line',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 34, note: "Square and Cube Roots" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 35, note: "Comparing Irrationals" },
      ],
    },
    {
      id: "8.rn.3",
      tpiCode: "8.2C",
      name: "Scientific Notation",
      description:
        "Convert between standard decimal notation and scientific notation, including negative exponents for very small numbers. Express numbers in scientific notation and interpret the magnitude of a number written in scientific notation.",
      gradeLevel: 8,
      strand: "Number & Operations",
      difficulty: 2,
      prerequisites: ["7.ns.3"],
      sampleProblems: [
        "Write 3,420,000 in scientific notation.",
        "Write 6.07 x 10^-5 in standard decimal notation.",
        "The mass of a proton is about 1.673 x 10^-27 kg. Is this a very small or very large number? Explain.",
      ],
      isVerifiable: true,
      order: 3,
      nineWeeks: 1,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 33, note: "Scientific Notation" },
      ],
    },
    {
      id: "8.rn.4",
      tpiCode: "8.2D",
      name: "Ordering Real Numbers Including Irrationals",
      description:
        "Order a set of real numbers that includes integers, fractions, decimals, square roots, and irrationals such as pi. Justify the ordering by approximating irrationals and comparing equivalent forms.",
      gradeLevel: 8,
      strand: "Number & Operations",
      difficulty: 2,
      prerequisites: ["8.rn.1", "8.rn.2", "7.ns.2"],
      sampleProblems: [
        "Order from least to greatest: 3.5, sqrt(11), 10/3, pi.",
        "Order from greatest to least: -sqrt(5), -2.3, -7/3, -2.1.",
        "Place sqrt(2), 1.5, 7/5, and sqrt(3) in order from least to greatest. Justify with decimal approximations.",
      ],
      isVerifiable: true,
      order: 4,
      nineWeeks: 1,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 35, note: "Comparing Irrationals" },
      ],
    },

    // ─── Strand 2: Proportional Relationships & Slope (TEKS 8.4–8.5) ─────
    {
      id: "8.sl.1",
      tpiCode: "8.4A",
      name: "Slope from Similar Right Triangles",
      description:
        "Use similar right triangles drawn between two points on a line to develop an understanding that slope (m) is the same for any two points on the line. Recognize slope as the constant ratio of vertical change to horizontal change.",
      gradeLevel: 8,
      strand: "Proportionality",
      difficulty: 2,
      prerequisites: ["7.lr.2", "7.pg.2"],
      sampleProblems: [
        "A line passes through (0, 1), (2, 4), and (4, 7). Draw two similar right triangles using these points and show that the ratio rise/run is the same for both.",
        "Two right triangles are drawn on the line y = 2x - 1: one between (1, 1) and (3, 5), another between (3, 5) and (6, 11). Confirm that both yield the same slope.",
        "Explain why the slope of a line is constant by appealing to similar right triangles.",
      ],
      isVerifiable: true,
      order: 5,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 57, note: "Slope" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 50, note: "Similar Figures and Scale Drawings" },
      ],
    },
    {
      id: "8.sl.2",
      tpiCode: "8.4B",
      name: "Graphing Proportional Relationships and Unit Rate as Slope",
      description:
        "Graph proportional relationships and interpret the unit rate as the slope of the line that models the relationship. Recognize that the graph of a proportional relationship is a line through the origin with slope equal to the constant of proportionality.",
      gradeLevel: 8,
      strand: "Proportionality",
      difficulty: 2,
      prerequisites: ["7.pr.1", "8.sl.1"],
      sampleProblems: [
        "A car travels at a constant speed of 55 miles per hour. Graph the relationship between hours (x) and miles (y), and identify the slope. What does the slope represent?",
        "On a graph, a proportional relationship passes through (0, 0) and (4, 10). What is the unit rate?",
        "A bakery sells 3 cookies for $2.25. Graph the relationship between number of cookies and cost. What is the unit rate as a slope?",
      ],
      isVerifiable: true,
      order: 6,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 57, note: "Slope" },
      ],
    },
    {
      id: "8.sl.3",
      tpiCode: "8.4C",
      name: "Rate of Change and y-Intercept from Tables and Graphs",
      description:
        "Use data from a table or graph to determine the rate of change (slope) and y-intercept of a linear relationship. Interpret both values in terms of a real-world context.",
      gradeLevel: 8,
      strand: "Proportionality",
      difficulty: 2,
      prerequisites: ["7.lr.2", "7.lr.3", "8.sl.2"],
      sampleProblems: [
        "From the table x: 0, 2, 4, 6 and y: 5, 11, 17, 23, find the rate of change and y-intercept. Write the linear equation.",
        "A line on a graph passes through (0, -3) and (4, 5). Determine the slope and y-intercept and write the equation.",
        "A gym membership costs $35 to join plus $20 per month. Identify the rate of change and the y-intercept and explain what each represents.",
      ],
      isVerifiable: true,
      order: 7,
      nineWeeks: 1,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },
    {
      id: "8.sl.4",
      tpiCode: "8.5A",
      name: "Proportional Linear Situations (y = kx)",
      description:
        "Represent linear proportional situations with tables, graphs, and equations of the form y = kx. Identify k as the constant of proportionality and confirm that the graph passes through the origin.",
      gradeLevel: 8,
      strand: "Proportionality",
      difficulty: 2,
      prerequisites: ["7.pr.1", "8.sl.2"],
      sampleProblems: [
        "Mia earns $9 per hour babysitting. Write an equation in the form y = kx for her earnings y after x hours. Make a table for 0–5 hours and graph the line.",
        "A printer prints 12 pages per minute. Represent this proportional situation with a table, graph, and equation.",
        "A recipe calls for 3 cups of flour per loaf. Write y = kx, then determine the flour needed for 8 loaves.",
      ],
      isVerifiable: true,
      order: 8,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },
    {
      id: "8.sl.5",
      tpiCode: "8.5B",
      name: "Non-Proportional Linear Situations (y = mx + b)",
      description:
        "Represent linear non-proportional situations with tables, graphs, and equations of the form y = mx + b, where b is not zero. Connect the y-intercept to a starting value or fixed cost in context.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.lr.3", "8.sl.4"],
      sampleProblems: [
        "A taxi charges a $3 base fare plus $2 per mile. Write y = mx + b, make a table for 0–5 miles, and graph the line.",
        "A pool contains 50 gallons of water and is filled at a rate of 8 gallons per minute. Write an equation, make a table, and graph the relationship.",
        "Compare y = 4x and y = 4x + 6 on the same graph. How are the two lines alike, and how do they differ?",
      ],
      isVerifiable: true,
      order: 9,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },
    {
      id: "8.sl.6",
      tpiCode: "8.5E",
      name: "Solving Real-World Linear Problems",
      description:
        "Solve real-world problems involving both proportional and non-proportional linear relationships. Set up equations from context, solve, and interpret the solution in terms of the original situation.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 3,
      prerequisites: ["8.sl.4", "8.sl.5", "7.ee.3"],
      sampleProblems: [
        "A phone plan costs $25 per month plus $0.10 per text. Write an equation for the monthly cost. If your bill was $43.50, how many texts did you send?",
        "A candle is 9 inches tall and burns at a rate of 0.5 inches per hour. Write an equation for the height after x hours. After how many hours is the candle 3 inches tall?",
        "Tickets to a fair cost $5 admission plus $2 per ride. If you spent $19, how many rides did you take?",
      ],
      isVerifiable: true,
      order: 10,
      nineWeeks: 2,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },
    {
      id: "8.sl.7",
      tpiCode: "8.5F",
      name: "Distinguishing Proportional vs. Non-Proportional Linear Functions",
      description:
        "Distinguish between proportional and non-proportional linear relationships from a table, graph, equation, or verbal description. Use the y-intercept and the ratio y/x as deciding criteria.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.pr.2", "8.sl.4", "8.sl.5"],
      sampleProblems: [
        "Does the equation y = 4x + 1 represent a proportional or non-proportional relationship? Explain.",
        "From a table x: 1, 2, 3, 4 and y: 5, 10, 15, 20, determine whether the relationship is proportional. Justify.",
        "A graph passes through (0, 3) and (2, 7). Is the relationship proportional? Explain.",
      ],
      isVerifiable: true,
      order: 11,
      nineWeeks: 2,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },
    {
      id: "8.sl.8",
      tpiCode: "8.5H",
      name: "Identifying Examples of Proportional and Non-Proportional Functions",
      description:
        "Identify real-world examples of proportional and non-proportional linear functions. Describe the defining feature of each (constant ratio vs. fixed starting value).",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["8.sl.7"],
      sampleProblems: [
        "Which situation is proportional? (a) A jogger runs 5 miles per hour. (b) A streaming service charges $10 plus $1 per movie. Justify your choice.",
        "Give one real-world example of a proportional function and one of a non-proportional linear function.",
        "Which equation is proportional: y = 7x, y = 7x + 2, or y = 7? Explain.",
      ],
      isVerifiable: true,
      order: 12,
      nineWeeks: 2,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },
    {
      id: "8.sl.9",
      tpiCode: "8.5I",
      name: "Writing y = mx + b from Verbal, Table, or Graph",
      description:
        "Write an equation in the form y = mx + b to model a linear relationship presented verbally, in a table, or as a graph. Identify slope and y-intercept first, then assemble the equation.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["8.sl.3", "8.sl.5"],
      sampleProblems: [
        "Write an equation in y = mx + b form for: 'A landscaper charges $40 for the visit plus $25 per hour of work.'",
        "From a table x: 0, 1, 2, 3 and y: -2, 1, 4, 7, write the linear equation.",
        "A graph shows a line through (0, -1) and (3, 5). Write its equation in y = mx + b form.",
      ],
      isVerifiable: true,
      order: 13,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },

    // ─── Strand 3: Functions (TEKS 8.5G) ─────────────────────────────────
    {
      id: "8.fn.1",
      tpiCode: "8.5G",
      name: "Identifying Functions",
      description:
        "Identify functions using sets of ordered pairs, tables, mappings, and graphs. Apply the rule that each input must correspond to exactly one output and use the vertical line test on graphs.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.lr.1"],
      sampleProblems: [
        "Is the set of ordered pairs {(1, 2), (2, 4), (3, 6), (1, 5)} a function? Explain.",
        "A mapping diagram shows: 1 -> 3, 2 -> 5, 3 -> 7, 4 -> 5. Is this a function? Why or why not?",
        "Apply the vertical line test to the graph of x = y^2. Is it a function? Justify.",
      ],
      isVerifiable: true,
      order: 14,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'function-mapping',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },

    // ─── Strand 4: Bivariate Data (TEKS 8.5C–D, 8.11) ────────────────────
    {
      id: "8.sc.1",
      tpiCode: "8.5C",
      name: "Contrasting Bivariate Sets for Linear Association",
      description:
        "Contrast bivariate sets of data that suggest a linear relationship with those that do not. Recognize positive, negative, and no association, and describe the strength of the association from a scatterplot.",
      gradeLevel: 8,
      strand: "Data Analysis & Statistics",
      difficulty: 2,
      prerequisites: ["7.lr.2"],
      sampleProblems: [
        "A scatterplot shows hours studied vs. test score; another shows shoe size vs. test score. Which suggests a linear relationship? Describe the association.",
        "Describe the association (positive, negative, or none) shown in a scatterplot of outdoor temperature vs. hot chocolate sales.",
        "Sketch two scatterplots: one with a strong negative linear association, and one with no association.",
      ],
      isVerifiable: true,
      order: 15,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'data-display',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [51, 56], unit: "Statistics and Probability" },
      ],
    },
    {
      id: "8.sc.2",
      tpiCode: "8.5D",
      name: "Trend Lines and Making Predictions",
      description:
        "Use a trend (line of best fit) on a scatterplot to make predictions about bivariate data. Read values from the trend line and interpret predictions in context.",
      gradeLevel: 8,
      strand: "Data Analysis & Statistics",
      difficulty: 2,
      prerequisites: ["8.sc.1", "8.sl.3"],
      sampleProblems: [
        "A trend line for the relationship between hours studied (x) and test score (y) is y = 8x + 50. Predict the score for a student who studies 6 hours.",
        "A scatterplot shows a trend line passing through (0, 30) and (10, 80). Use the trend line to predict y when x = 4.",
        "Why is a prediction from a trend line less reliable when x is far outside the range of the data?",
      ],
      isVerifiable: true,
      order: 16,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'data-display',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [51, 56], unit: "Statistics and Probability" },
      ],
    },
    {
      id: "8.sc.3",
      tpiCode: "8.11A",
      name: "Constructing Scatterplots",
      description:
        "Construct a scatterplot for a set of bivariate data and describe the association (positive, negative, none) along with general clustering or outliers. Label axes appropriately and choose suitable scales.",
      gradeLevel: 8,
      strand: "Data Analysis & Statistics",
      difficulty: 2,
      prerequisites: ["8.sc.1"],
      sampleProblems: [
        "Construct a scatterplot for the data set (hours practiced, free throws made): (1, 4), (2, 5), (3, 7), (4, 8), (5, 9), (6, 11).",
        "Plot the bivariate data (x, y): (0, 12), (1, 10), (2, 9), (3, 7), (4, 5). Describe the association.",
        "Make a scatterplot of student heights (in) vs. arm spans (in) for 10 classmates. Describe the trend.",
      ],
      isVerifiable: true,
      order: 17,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'data-display',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [51, 56], unit: "Statistics and Probability" },
      ],
    },
    {
      id: "8.sc.4",
      tpiCode: "8.11B",
      name: "Mean Absolute Deviation (MAD)",
      description:
        "Calculate the mean absolute deviation (MAD) of a small data set as a measure of variability. Interpret MAD as the average distance of each data point from the mean.",
      gradeLevel: 8,
      strand: "Data Analysis & Statistics",
      difficulty: 2,
      prerequisites: ["7.ns.4"],
      sampleProblems: [
        "Find the MAD of the data set: 4, 7, 8, 10, 11.",
        "Two basketball players average 18 points per game. Player A has MAD 2.4; player B has MAD 6.1. Which player is more consistent? Explain.",
        "A data set has mean 50 and values 42, 47, 50, 53, 58. Calculate the MAD.",
      ],
      isVerifiable: true,
      order: 18,
      nineWeeks: 3,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [51, 56], unit: "Statistics and Probability" },
      ],
    },

    // ─── Strand 5: One-Variable Equations & Systems (TEKS 8.8–8.9) ───────
    {
      id: "8.eq.1",
      tpiCode: "8.8A",
      name: "Writing Equations with Variables on Both Sides",
      description:
        "Write one-variable equations or inequalities with variables on both sides that represent problems involving rational coefficients. Define variables, translate verbal phrases, and check that the equation matches the situation.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 2,
      prerequisites: ["7.ee.4"],
      sampleProblems: [
        "Write an equation: 'Five less than twice a number is the same as three times the number plus 4.'",
        "A gym charges $30 per month plus $5 per class. Another gym charges $20 per month plus $7 per class. Write an equation to find the number of classes for which the costs are equal.",
        "The perimeter of a rectangle equals the perimeter of a square. The rectangle has length (x + 4) and width (x - 1); the square has side length (x + 2). Write the equation.",
      ],
      isVerifiable: true,
      order: 19,
      nineWeeks: 3,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 37, note: "Solving Multistep Equations" },
      ],
    },
    {
      id: "8.eq.2",
      tpiCode: "8.8B",
      name: "Solving Equations with Variables on Both Sides",
      description:
        "Solve one-variable equations with variables on both sides, including those that require the distributive property and combining like terms. Verify solutions by substitution.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 3,
      prerequisites: ["7.ee.2", "7.ee.3", "8.eq.1"],
      sampleProblems: [
        "Solve for x: 5x - 7 = 2x + 11.",
        "Solve: 3(2x + 1) = 4x + 11.",
        "Solve: -2(x - 4) + 3x = 5x - 6.",
      ],
      isVerifiable: true,
      order: 20,
      nineWeeks: 3,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 37, note: "Solving Multistep Equations" },
      ],
    },
    {
      id: "8.eq.3",
      tpiCode: "8.8C",
      name: "Equations with One, None, or Infinitely Many Solutions",
      description:
        "Determine whether a linear equation has one solution, no solution, or infinitely many solutions by simplifying both sides and comparing. Connect to the structure of the resulting statement (e.g., 0 = 0, 0 = 5, x = number).",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 3,
      prerequisites: ["8.eq.2"],
      sampleProblems: [
        "How many solutions does 4(x - 2) = 4x - 8 have? Justify.",
        "Determine the number of solutions: 3x + 6 = 3x + 9.",
        "Determine the number of solutions: 2(x + 3) = 5x - 3 and solve if possible.",
      ],
      isVerifiable: true,
      order: 21,
      nineWeeks: 3,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 37, note: "Solving Multistep Equations" },
      ],
    },
    {
      id: "8.sy.1",
      tpiCode: "8.9A",
      name: "Solutions of Linear Systems from Graphs",
      description:
        "Identify the solution of a system of two linear equations from the intersection point of their graphs. Verify the solution algebraically by substitution into both equations.",
      gradeLevel: 8,
      strand: "Algebra",
      difficulty: 3,
      prerequisites: ["8.sl.5", "8.sl.9"],
      sampleProblems: [
        "Graph the system y = 2x + 1 and y = -x + 4. Identify the solution and verify by substitution.",
        "Two lines intersect at (3, 2) on a coordinate plane. What is the solution to the system?",
        "A graph shows the lines y = x + 1 and y = -x + 5. State the solution.",
      ],
      isVerifiable: true,
      order: 22,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 58, note: "Linear Equations and Functions" },
      ],
    },

    // ─── Strand 6: 3D Geometry & Pythagorean (TEKS 8.6–8.7) ──────────────
    {
      id: "8.vl.1",
      tpiCode: "8.6A/8.7A",
      name: "Volume of Cylinders, Cones, and Spheres",
      description:
        "Use formulas to determine the volume of cylinders (V = pi r^2 h), cones (V = (1/3) pi r^2 h), and spheres (V = (4/3) pi r^3). Solve real-world problems and connect the relationship between cylinder and cone of the same base and height.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.pg.1"],
      sampleProblems: [
        "Find the volume of a cylinder with radius 4 cm and height 10 cm. Use pi approx 3.14.",
        "Find the volume of a cone with radius 6 in and height 9 in. Round to the nearest tenth.",
        "Find the volume of a sphere with radius 5 cm. How does it compare to the volume of a cylinder with radius 5 cm and height 10 cm?",
      ],
      isVerifiable: true,
      order: 23,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 48, note: "Volume" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapters: [46, 47], note: "3D Figures" },
      ],
    },
    {
      id: "8.vl.2",
      tpiCode: "8.7B",
      name: "Surface Area of Prisms and Cylinders",
      description:
        "Find the lateral and total surface area of rectangular prisms, triangular prisms, and cylinders. Use nets to visualize each face and apply appropriate formulas.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.pg.1"],
      sampleProblems: [
        "Find the total surface area of a rectangular prism with dimensions 5 cm by 3 cm by 8 cm.",
        "Find the lateral and total surface area of a cylinder with radius 3 in and height 12 in.",
        "A triangular prism has a right-triangle base with legs 6 cm and 8 cm (hypotenuse 10 cm) and a length of 15 cm. Find the total surface area.",
      ],
      isVerifiable: true,
      order: 24,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 49, note: "Surface Area" },
      ],
    },
    {
      id: "8.py.1",
      tpiCode: "8.6C",
      name: "Models of the Pythagorean Theorem",
      description:
        "Use models, including squares built on the sides of a right triangle, to explain the Pythagorean theorem (a^2 + b^2 = c^2). Verify the relationship by computing areas of the squares on the legs and hypotenuse.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["8.rn.1"],
      sampleProblems: [
        "A right triangle has legs 3 and 4 units. Draw squares on each side and show that the sum of the areas on the legs equals the area of the square on the hypotenuse.",
        "Use a square-on-each-side model to explain why a^2 + b^2 = c^2 for any right triangle.",
        "Given a right triangle with legs 5 and 12, find the area of the square on the hypotenuse without first finding the hypotenuse length.",
      ],
      isVerifiable: true,
      order: 25,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 44, note: "Pythagorean Theorem" },
      ],
    },
    {
      id: "8.py.2",
      tpiCode: "8.7C",
      name: "Applying the Pythagorean Theorem and Its Converse",
      description:
        "Use the Pythagorean theorem and its converse to find missing side lengths of right triangles and to determine whether a given triangle is a right triangle. Apply to real-world problems including ladders, diagonals, and distances.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 3,
      prerequisites: ["8.py.1", "8.rn.2"],
      sampleProblems: [
        "Triangle ABC has sides AB = 6, AC = 8, and a right angle at A. Find BC.",
        "A 13-ft ladder leans against a wall, with its base 5 ft from the wall. How high up the wall does the ladder reach?",
        "Is a triangle with side lengths 9, 12, and 15 a right triangle? Justify using the converse of the Pythagorean theorem.",
      ],
      isVerifiable: true,
      order: 26,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 44, note: "Pythagorean Theorem" },
      ],
    },
    {
      id: "8.py.3",
      tpiCode: "8.7D",
      name: "Distance Between Two Points on the Coordinate Plane",
      description:
        "Determine the distance between two points on a coordinate plane using the Pythagorean theorem. Treat the segment between the points as the hypotenuse of a right triangle whose legs are horizontal and vertical distances.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 3,
      prerequisites: ["8.py.2"],
      sampleProblems: [
        "Find the distance between (1, 2) and (5, 5).",
        "Find the distance between (-3, 4) and (2, -8).",
        "A robot starts at (0, 0) and moves to (9, 12). How far has it traveled in a straight line?",
      ],
      isVerifiable: true,
      order: 27,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 44, note: "Pythagorean Theorem" },
      ],
    },

    // ─── Strand 7: 2D Geometry & Transformations (TEKS 8.3, 8.8D, 8.10) ──
    {
      id: "8.ag.1",
      tpiCode: "8.8D",
      name: "Angle Relationships: Parallel Lines, Triangle Sum, AA Similarity",
      description:
        "Use informal arguments to establish angle relationships: parallel lines cut by a transversal (corresponding, alternate interior, alternate exterior, same-side interior), the triangle angle sum (180 degrees), the exterior angle theorem, and AA similarity for triangles.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.pg.2"],
      sampleProblems: [
        "Parallel lines l and m are cut by transversal t. If one of the angles formed is 65 degrees, find the measures of all eight angles and name each pair.",
        "Two angles of a triangle are 47 degrees and 68 degrees. Find the third angle.",
        "Triangle ABC has angles 50 and 60 degrees; triangle DEF has angles 50 and 70 degrees. Are they similar by AA? Justify.",
      ],
      isVerifiable: true,
      order: 28,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 41, note: "Angles" },
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 50, note: "Similar Figures and Scale Drawings" },
      ],
    },
    {
      id: "8.dl.1",
      tpiCode: "8.3A",
      name: "Dilations on the Coordinate Plane",
      description:
        "Generalize that the ratio of corresponding sides of similar shapes are proportional. Perform dilations of two-dimensional figures on a coordinate plane using a scale factor with the center at the origin and describe the effect on coordinates as (x, y) -> (kx, ky).",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["7.pg.2", "8.ag.1"],
      sampleProblems: [
        "Dilate triangle with vertices A(2, 1), B(4, 1), C(2, 3) by a scale factor of 2 with center at the origin. Give the new coordinates.",
        "A square has vertices (1, 1), (1, 3), (3, 3), (3, 1). Dilate by scale factor 1/2 about the origin. Plot original and image.",
        "A triangle is dilated by scale factor 3 from the origin. The image has a vertex at (9, -6). What was the corresponding vertex on the original?",
      ],
      isVerifiable: true,
      order: 29,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 50, note: "Similar Figures and Scale Drawings" },
      ],
    },
    {
      id: "8.tr.1",
      tpiCode: "8.10A",
      name: "Translations on the Coordinate Plane",
      description:
        "Perform translations of two-dimensional figures on the coordinate plane. Describe the effect on coordinates using rules such as (x, y) -> (x + a, y + b) and recognize that translations preserve size and orientation.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 1,
      prerequisites: ["7.lr.1"],
      sampleProblems: [
        "Translate triangle ABC with vertices A(1, 2), B(4, 2), C(4, 5) using the rule (x, y) -> (x - 3, y + 4). Give the image coordinates.",
        "A rectangle with vertices (0, 0), (5, 0), (5, 2), (0, 2) is translated 6 units left and 3 units down. Give the image coordinates.",
        "Describe the translation that maps (2, -3) to (-1, 4) using a rule of the form (x, y) -> (x + a, y + b).",
      ],
      isVerifiable: true,
      order: 30,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "8.tr.2",
      tpiCode: "8.10B",
      name: "Reflections on the Coordinate Plane",
      description:
        "Perform reflections of two-dimensional figures across the x-axis, y-axis, and lines y = x or y = -x. Describe the effect on coordinates using rules such as (x, y) -> (x, -y) and (x, y) -> (-x, y).",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 2,
      prerequisites: ["8.tr.1"],
      sampleProblems: [
        "Reflect triangle with vertices A(2, 3), B(5, 1), C(4, 6) over the x-axis. Give the image coordinates.",
        "Reflect the point (-4, 7) over the y-axis. What are the new coordinates?",
        "Reflect quadrilateral with vertices (1, 2), (3, 4), (5, 2), (3, 0) over the line y = x. Give the image vertices.",
      ],
      isVerifiable: true,
      order: 31,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "8.tr.3",
      tpiCode: "8.10C/8.10D",
      name: "Rotations on the Coordinate Plane",
      description:
        "Perform rotations of 90, 180, and 270 degrees about the origin on the coordinate plane. Describe the effect on coordinates using rules: 90 degrees CCW: (x, y) -> (-y, x); 180 degrees: (x, y) -> (-x, -y); 270 degrees CCW: (x, y) -> (y, -x). Recognize that rotations preserve size and shape.",
      gradeLevel: 8,
      strand: "Geometry & Measurement",
      difficulty: 3,
      prerequisites: ["8.tr.1", "8.tr.2"],
      sampleProblems: [
        "Rotate triangle ABC with vertices A(2, 1), B(5, 1), C(2, 4) 90 degrees counterclockwise about the origin. Give the image coordinates.",
        "Rotate the point (3, -5) 180 degrees about the origin. What are the new coordinates?",
        "Rotate the rectangle with vertices (1, 2), (4, 2), (4, 5), (1, 5) 270 degrees counterclockwise about the origin. Give the image vertices.",
      ],
      isVerifiable: true,
      order: 32,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },

    // ─── Strand 8: Personal Financial Literacy (TEKS 8.12) ───────────────
    {
      id: "8.pf.1",
      tpiCode: "8.12A",
      name: "Simple vs. Compound Interest",
      description:
        "Compare simple and compound interest. Use the simple interest formula I = Prt and the compound interest formula A = P(1 + r/n)^(nt) to compute growth over time and explain why compound interest grows faster.",
      gradeLevel: 8,
      strand: "Personal Financial Literacy",
      difficulty: 3,
      prerequisites: ["7.pr.5"],
      sampleProblems: [
        "You invest $1,000 at 5% annual simple interest for 4 years. How much interest do you earn? Compare to 5% interest compounded annually for 4 years.",
        "How much will $2,000 grow to in 3 years at 4% simple interest? At 4% compounded annually?",
        "Explain in your own words why compound interest grows faster than simple interest over time.",
      ],
      isVerifiable: true,
      order: 33,
      nineWeeks: 4,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 25, note: "Simple Interest" },
      ],
    },
    {
      id: "8.pf.2",
      tpiCode: "8.12C/8.12D",
      name: "Credit Cards and the Cost of Credit",
      description:
        "Explain how credit cards work, including interest rates (APR), minimum payments, and how carrying a balance can quickly add to the cost of a purchase. Calculate the cost of credit on a sample balance over time.",
      gradeLevel: 8,
      strand: "Personal Financial Literacy",
      difficulty: 2,
      prerequisites: ["8.pf.1"],
      sampleProblems: [
        "A $500 credit card balance has an APR of 18%. If only the $25 minimum payment is made each month, estimate how much interest accumulates in one year.",
        "Explain the difference between paying the full balance each month versus paying only the minimum.",
        "List two advantages and two disadvantages of using a credit card to make a $300 purchase.",
      ],
      isVerifiable: true,
      order: 34,
      nineWeeks: 4,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 25, unit: "Expressions and Equations", note: "Simple Interest — closest available; PFL topics covered conceptually" },
      ],
    },
    {
      id: "8.pf.3",
      tpiCode: "8.12G",
      name: "Financial Planning: Paying for College",
      description:
        "Estimate the cost of attending college (tuition, room and board, fees, books) and analyze ways to pay, including savings, grants, scholarships, work-study, and student loans. Compare options and explain trade-offs.",
      gradeLevel: 8,
      strand: "Personal Financial Literacy",
      difficulty: 2,
      prerequisites: ["8.pf.1"],
      sampleProblems: [
        "A four-year university costs $24,000 per year. Estimate the total cost of attendance for four years. If a family saves $300 per month starting when a child is born, how much will they save by age 18 (ignoring interest)?",
        "Compare paying for college with a $20,000 scholarship versus a $20,000 student loan at 6% simple interest paid over 10 years. Which costs more in the end?",
        "List three sources of money to pay for college and explain one advantage of each.",
      ],
      isVerifiable: false,
      order: 35,
      nineWeeks: 4,
      bookRefs: [
        { title: "The Big Fat Middle School Math Workbook", isbn: "9781523513581", chapter: 25, unit: "Expressions and Equations", note: "Simple Interest — closest available; PFL topics covered conceptually" },
      ],
    },
  ],
};
