import { GradeCurriculum } from '../../../types';

export const grade9Algebra1Curriculum: GradeCurriculum = {
  grade: 9,
  label: "Algebra 1 (Honors)",
  topics: [
    // ─── Strand 1: Solving Equations & Inequalities in One Variable (TEKS A.5, A.12E) ─
    {
      id: "a1.le.1",
      tpiCode: "A.5A",
      name: "Solving Multi-Step Linear Equations",
      description:
        "Solve linear equations in one variable, including those requiring the distributive property and those with variables on both sides. Combine like terms, clear fractions, and verify solutions by substitution.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 1,
      prerequisites: ["8.eq.2", "8.eq.3"],
      sampleProblems: [
        "Solve for x: 4x - 9 = 2x + 15.",
        "Solve: 3(2x - 5) + 4 = 7x - 9.",
        "Solve: (1/2)(6x + 8) = 5x - 10.",
      ],
      isVerifiable: true,
      order: 1,
      nineWeeks: 1,
    },
    {
      id: "a1.le.2",
      tpiCode: "A.5B",
      name: "Solving Linear Inequalities in One Variable",
      description:
        "Solve linear inequalities in one variable, including those requiring the distributive property and those with variables on both sides. Reverse the inequality symbol when multiplying or dividing by a negative, and graph solution sets on a number line.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.le.1"],
      sampleProblems: [
        "Solve and graph the solution on a number line: 3x - 7 >= 2x + 5.",
        "Solve: -4(x - 2) > 12. Explain why the inequality symbol reverses.",
        "Solve and graph: 5 - 2x <= 3x + 20.",
      ],
      isVerifiable: true,
      order: 2,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'number-line',
    },
    {
      id: "a1.le.3",
      tpiCode: "A.12E",
      name: "Literal Equations and Formulas",
      description:
        "Solve mathematical and scientific formulas, and other literal equations, for a specified variable. Apply the same inverse-operation steps used for numeric equations while treating the other variables as constants.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.le.1"],
      sampleProblems: [
        "Solve the perimeter formula P = 2l + 2w for w.",
        "Solve A = (1/2)bh for h.",
        "Solve y = mx + b for x.",
      ],
      isVerifiable: true,
      order: 3,
      nineWeeks: 1,
    },

    // ─── Strand 2: Introduction to Functions (TEKS A.2A, A.12A–B) ────────
    {
      id: "a1.fn.1",
      tpiCode: "A.12A/A.12B",
      name: "Relations, Functions, and Function Notation",
      description:
        "Decide whether relations represented verbally, tabularly, graphically, and symbolically define a function, using the each-input-has-exactly-one-output rule and the vertical line test. Evaluate functions expressed in function notation for given elements of their domains.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 1,
      prerequisites: ["8.fn.1"],
      sampleProblems: [
        "Is the relation {(2, 3), (4, 5), (6, 7), (2, 9)} a function? Explain.",
        "Given f(x) = 3x - 7, find f(5), f(0), and f(-2).",
        "Given g(x) = x^2 + 2x, evaluate g(-3). Then use a mapping diagram of 1 -> 4, 2 -> 4, 3 -> 6 to decide whether the mapping is a function.",
      ],
      isVerifiable: true,
      order: 4,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'function-mapping',
    },
    {
      id: "a1.fn.2",
      tpiCode: "A.2A",
      name: "Domain and Range of Linear Functions",
      description:
        "Determine the domain and range of linear functions in mathematical problems, and determine reasonable domain and range values for real-world situations, both continuous and discrete. Represent domain and range using inequalities.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.fn.1"],
      sampleProblems: [
        "A graph shows the segment of a line from (0, 2) to (6, 14). Write the domain and range using inequalities.",
        "A babysitter earns $12 per hour and can work at most 20 hours per week. Give a reasonable domain and range for E(h) = 12h using inequalities. Is the domain continuous or discrete?",
        "Movie tickets cost $9 each and the theater holds 150 people. For C(t) = 9t, give a reasonable domain and range. Is this situation continuous or discrete?",
      ],
      isVerifiable: true,
      order: 5,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },

    // ─── Strand 3: Linear Functions (TEKS A.2B–G, A.3A–C, A.3E) ──────────
    {
      id: "a1.lf.1",
      tpiCode: "A.3A/A.3B",
      name: "Slope and Rate of Change",
      description:
        "Determine the slope of a line given a table of values, a graph, two points on the line, or an equation written in various forms. Calculate the rate of change of a linear function in mathematical and real-world problems and interpret it in context.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 1,
      prerequisites: ["8.sl.1", "8.sl.3"],
      sampleProblems: [
        "Find the slope of the line through (-2, 5) and (4, -7).",
        "Find the slope of the line 6x - 3y = 12.",
        "From the table x: 1, 3, 5, 7 and y: 4, 10, 16, 22, find the rate of change. If x is hours worked and y is dollars earned, what does the rate of change represent?",
      ],
      isVerifiable: true,
      order: 6,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.lf.2",
      tpiCode: "A.3C",
      name: "Graphing Linear Functions and Key Features",
      description:
        "Graph linear functions on the coordinate plane and identify key features, including the x-intercept, y-intercept, zeros, and slope, in mathematical and real-world problems. Graph from slope-intercept form and from standard form using intercepts.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.lf.1", "8.sl.5"],
      sampleProblems: [
        "Graph f(x) = -2x + 6 and identify the slope, y-intercept, x-intercept, and the zero of the function.",
        "Graph 3x + 4y = 12 by finding both intercepts.",
        "Graph y = (2/3)x - 4. What is the zero of the function?",
      ],
      isVerifiable: true,
      order: 7,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.lf.3",
      tpiCode: "A.2B",
      name: "Writing Linear Equations in Multiple Forms",
      description:
        "Write linear equations in two variables in various forms, including y = mx + b, Ax + By = C, and y - y1 = m(x - x1), given one point and the slope or given two points. Convert fluently between forms.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.lf.1", "8.sl.9"],
      sampleProblems: [
        "Write the equation of the line with slope 3 through (2, -5) in point-slope form, then convert it to slope-intercept form.",
        "Write the equation of the line through (1, 4) and (3, 10) in slope-intercept form.",
        "Rewrite y = (3/4)x - 2 in standard form Ax + By = C using integer coefficients.",
      ],
      isVerifiable: true,
      order: 8,
      nineWeeks: 1,
    },
    {
      id: "a1.lf.4",
      tpiCode: "A.2C",
      name: "Writing Linear Equations from Tables, Graphs, and Descriptions",
      description:
        "Write linear equations in two variables given a table of values, a graph, or a verbal description. Identify the rate of change and initial value from each representation before assembling the equation.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.lf.3"],
      sampleProblems: [
        "From the table x: 0, 2, 4, 6 and y: 3, 7, 11, 15, write the linear equation in y = mx + b form.",
        "A graph shows a line through (0, 5) and (4, -3). Write its equation.",
        "A rock climber descends at 8 feet per minute from a ledge 120 feet high. Write an equation for the height y after x minutes.",
      ],
      isVerifiable: true,
      order: 9,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'table',
    },
    {
      id: "a1.lf.5",
      tpiCode: "A.2E/A.2F/A.2G",
      name: "Parallel and Perpendicular Lines",
      description:
        "Write the equation of a line that contains a given point and is parallel or perpendicular to a given line, including lines parallel or perpendicular to the x-axis or y-axis. Determine whether the slope of a horizontal or vertical line is zero or undefined.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.lf.3"],
      sampleProblems: [
        "Write the equation of the line through (4, -1) that is parallel to y = 2x + 7.",
        "Write the equation of the line through (6, 2) that is perpendicular to y = -3x + 1.",
        "Write the equation of the vertical line through (5, -3). Is its slope zero or undefined?",
      ],
      isVerifiable: true,
      order: 10,
      nineWeeks: 1,
    },
    {
      id: "a1.lf.6",
      tpiCode: "A.3E",
      name: "Transformations of Linear Functions",
      description:
        "Determine the effects on the graph of the parent function f(x) = x when f(x) is replaced by af(x), f(x) + d, f(x - c), and f(bx) for specific values of a, b, c, and d. Describe each transformation as a vertical stretch, compression, reflection, or translation.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.lf.2"],
      sampleProblems: [
        "Describe how the graph of g(x) = x + 5 compares to the parent function f(x) = x.",
        "The parent function f(x) = x is transformed to g(x) = 3x. Describe the effect on the graph, then graph both lines on the same coordinate plane.",
        "Let f(x) = x. Write g(x) = f(x - 4) in simplest form and describe the transformation.",
      ],
      isVerifiable: true,
      order: 11,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },

    // ─── Strand 4: Direct Variation, Data & Arithmetic Sequences (TEKS A.2D, A.4, A.12C–D) ─
    {
      id: "a1.lf.7",
      tpiCode: "A.2D",
      name: "Direct Variation",
      description:
        "Write and solve equations involving direct variation (y = kx). Identify the constant of variation from tables, graphs, and verbal descriptions, and recognize that the graph of a direct variation is a line through the origin.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 1,
      prerequisites: ["8.sl.4"],
      sampleProblems: [
        "y varies directly with x, and y = 24 when x = 6. Find the constant of variation, write the equation, and find y when x = 10.",
        "Does the table x: 2, 4, 6 and y: 7, 14, 21 show direct variation? If so, write the equation.",
        "The distance a spring stretches varies directly with the weight attached. A 12-pound weight stretches it 3 inches. How far does a 20-pound weight stretch it?",
      ],
      isVerifiable: true,
      order: 12,
      nineWeeks: 2,
    },
    {
      id: "a1.dt.1",
      tpiCode: "A.4A/A.4B",
      name: "Correlation Coefficient, Association, and Causation",
      description:
        "Interpret the correlation coefficient r as a measure of the strength and direction of a linear association between two quantitative variables. Compare and contrast association and causation in real-world problems and explain why correlation alone does not prove causation.",
      gradeLevel: 9,
      strand: "Data & Statistics",
      difficulty: 2,
      prerequisites: ["8.sc.1", "8.sc.3"],
      sampleProblems: [
        "A data set of hours studied vs. test score has correlation coefficient r = 0.92. Describe the strength and direction of the linear association.",
        "Which r value indicates the strongest linear relationship: r = 0.65, r = -0.89, or r = 0.15? Justify your choice.",
        "Ice cream sales and drowning incidents both rise in the summer. Does this association prove that ice cream causes drowning? Explain the difference between association and causation.",
      ],
      isVerifiable: true,
      order: 13,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'data-display',
    },
    {
      id: "a1.dt.2",
      tpiCode: "A.4C",
      name: "Lines of Best Fit and Making Predictions",
      description:
        "Write linear functions that provide a reasonable fit to bivariate data, and use the fitted line to estimate solutions and make predictions in real-world problems. Interpret the slope and y-intercept of the fitted line in context.",
      gradeLevel: 9,
      strand: "Data & Statistics",
      difficulty: 2,
      prerequisites: ["a1.dt.1", "8.sc.2", "a1.lf.4"],
      sampleProblems: [
        "The line of best fit relating hours of practice (x) to words typed per minute (y) is y = 4.5x + 22. Predict the typing speed after 8 hours of practice.",
        "Draw a reasonable line of best fit through the scatterplot of (1, 3), (2, 5), (3, 6), (4, 9), (5, 10), and write its approximate equation.",
        "A best-fit line for car age in years (x) vs. value in dollars (y) is y = -1500x + 24000. Interpret the slope and y-intercept, then estimate the value of a 6-year-old car.",
      ],
      isVerifiable: true,
      order: 14,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'data-display',
    },
    {
      id: "a1.sq.1",
      tpiCode: "A.12C/A.12D",
      name: "Arithmetic Sequences",
      description:
        "Identify terms of arithmetic sequences given in function form using recursive processes, and write a formula for the nth term given several terms. Connect the common difference to the slope of a linear function.",
      gradeLevel: 9,
      strand: "Linear Functions & Equations",
      difficulty: 2,
      prerequisites: ["a1.fn.1", "a1.lf.4"],
      sampleProblems: [
        "Find the first four terms of the sequence defined by a(1) = 7 and a(n) = a(n-1) + 4 for n >= 2.",
        "Write a formula for the nth term of the arithmetic sequence 5, 12, 19, 26, ... Then find a(20).",
        "An arithmetic sequence has a(3) = 14 and a(7) = 30. Find the common difference and write the nth-term formula.",
      ],
      isVerifiable: true,
      order: 15,
      nineWeeks: 2,
    },

    // ─── Strand 5: Systems of Linear Equations (TEKS A.2I, A.3F–G, A.5C) ─
    {
      id: "a1.sy.1",
      tpiCode: "A.3F/A.3G",
      name: "Solving Systems of Equations by Graphing",
      description:
        "Graph systems of two linear equations in two variables on the coordinate plane and determine the solution if it exists, including systems with no solution or infinitely many solutions. Estimate solutions graphically in real-world problems.",
      gradeLevel: 9,
      strand: "Systems of Equations",
      difficulty: 2,
      prerequisites: ["8.sy.1", "a1.lf.2"],
      sampleProblems: [
        "Solve by graphing: y = 2x - 3 and y = -x + 6. Check the intersection point in both equations.",
        "Graph the system y = (1/2)x + 1 and 2y - x = 8. How many solutions does the system have? Explain.",
        "Gym A costs y = 10x + 30 and Gym B costs y = 15x, where x is months. Graph both and estimate when the total costs are equal.",
      ],
      isVerifiable: true,
      order: 16,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.sy.2",
      tpiCode: "A.5C",
      name: "Solving Systems by Substitution and Elimination",
      description:
        "Solve systems of two linear equations with two variables algebraically using substitution and elimination, including systems that require multiplying one or both equations before eliminating. Choose the more efficient method for a given system.",
      gradeLevel: 9,
      strand: "Systems of Equations",
      difficulty: 2,
      prerequisites: ["a1.sy.1", "a1.le.1"],
      sampleProblems: [
        "Solve by substitution: y = 3x - 5 and 2x + y = 10.",
        "Solve by elimination: 4x + 3y = 18 and 4x - 3y = 6.",
        "Solve using any algebraic method: 2x + 3y = 7 and 3x - 4y = 19.",
      ],
      isVerifiable: true,
      order: 17,
      nineWeeks: 2,
    },
    {
      id: "a1.sy.3",
      tpiCode: "A.2I/A.5C",
      name: "Writing and Solving Systems from Real-World Problems",
      description:
        "Write systems of two linear equations given a table of values, a graph, or a verbal description, and solve them for mathematical and real-world problems. Define both variables, solve with an appropriate method, and interpret the solution in context.",
      gradeLevel: 9,
      strand: "Systems of Equations",
      difficulty: 3,
      prerequisites: ["a1.sy.2"],
      sampleProblems: [
        "Movie tickets cost $8 for children and $12 for adults. A family bought 7 tickets for $68. Write and solve a system to find how many of each ticket they bought.",
        "The sum of two numbers is 41 and their difference is 9. Write and solve a system to find the numbers.",
        "A coffee shop sells lattes for $5 and drip coffees for $3. In one hour it sold 30 drinks for $118. Write and solve a system to find how many of each drink were sold.",
      ],
      isVerifiable: true,
      order: 18,
      nineWeeks: 2,
    },

    // ─── Strand 6: Linear Inequalities in Two Variables (TEKS A.2H, A.3D, A.3H) ─
    {
      id: "a1.in.1",
      tpiCode: "A.2H/A.3D",
      name: "Graphing Linear Inequalities in Two Variables",
      description:
        "Write linear inequalities in two variables given a table of values, a graph, or a verbal description, and graph their solution sets on the coordinate plane. Decide whether the boundary line is solid or dashed and which half-plane to shade by testing a point.",
      gradeLevel: 9,
      strand: "Systems of Equations",
      difficulty: 2,
      prerequisites: ["a1.le.2", "a1.lf.2"],
      sampleProblems: [
        "Graph the solution set of y > 2x - 4. Should the boundary line be solid or dashed? Explain.",
        "Graph y <= -(1/3)x + 2 and name one point in the solution set.",
        "Student tickets cost $4 and adult tickets cost $6, and a club needs to raise at least $240. Write an inequality relating student tickets x and adult tickets y.",
      ],
      isVerifiable: true,
      order: 19,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.in.2",
      tpiCode: "A.3H",
      name: "Systems of Linear Inequalities",
      description:
        "Graph the solution set of a system of two linear inequalities in two variables on the coordinate plane, identifying the overlapping region. Verify whether given points are solutions and write systems of inequalities from real-world constraints.",
      gradeLevel: 9,
      strand: "Systems of Equations",
      difficulty: 3,
      prerequisites: ["a1.in.1", "a1.sy.1"],
      sampleProblems: [
        "Graph the solution set of the system y >= x - 2 and y < -2x + 4. Shade the region that satisfies both inequalities.",
        "Is the point (1, 3) a solution of the system y > x + 1 and y <= -x + 5? Justify by substitution.",
        "You can work at most 20 hours per week at two jobs and need to earn at least $150. Job A pays $10 per hour (x hours) and Job B pays $8 per hour (y hours). Write a system of inequalities and graph the solution region.",
      ],
      isVerifiable: true,
      order: 20,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },

    // ─── Strand 7: Exponents & Exponential Functions (TEKS A.9, A.11B, A.12C–D) ─
    {
      id: "a1.ex.1",
      tpiCode: "A.11B",
      name: "Laws of Exponents",
      description:
        "Simplify numeric and algebraic expressions using the laws of exponents, including integral exponents (product, quotient, power, zero, and negative exponent rules) and rational exponents. Write answers using positive exponents.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 2,
      prerequisites: ["8.rn.3"],
      sampleProblems: [
        "Simplify: (x^4)(x^3) and m^6 / m^2.",
        "Simplify and write with positive exponents: (2a^3)^-2.",
        "Evaluate: 16^(1/2), 8^(2/3), and 5^0.",
      ],
      isVerifiable: true,
      order: 21,
      nineWeeks: 3,
    },
    {
      id: "a1.ex.2",
      tpiCode: "A.9A/A.9D",
      name: "Exponential Functions and Their Graphs",
      description:
        "Graph exponential functions of the form f(x) = ab^x that model growth and decay, and identify key features including the y-intercept and horizontal asymptote. Determine the domain and range and represent them using inequalities.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 2,
      prerequisites: ["a1.ex.1", "a1.fn.2"],
      sampleProblems: [
        "Graph f(x) = 2^x for x from -2 to 3. Identify the y-intercept and the horizontal asymptote.",
        "Graph f(x) = 8(1/2)^x. Is this growth or decay? State the domain and range using inequalities.",
        "What are the domain and range of f(x) = 3(2)^x? Write each as an inequality.",
      ],
      isVerifiable: true,
      order: 22,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.ex.3",
      tpiCode: "A.9B/A.9C",
      name: "Exponential Growth and Decay Models",
      description:
        "Write exponential functions in the form f(x) = ab^x to describe real-world situations involving growth and decay, and interpret the meaning of a (initial value) and b (growth or decay factor) in context. Convert percent growth or decay rates into the factor b.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 3,
      prerequisites: ["a1.ex.2"],
      sampleProblems: [
        "A car worth $28,000 loses 12% of its value each year. Write a function V(t) = ab^t for its value after t years and find the value after 5 years.",
        "A bacteria culture starts with 500 cells and doubles every hour. Write a function for the population after t hours. How many cells are there after 6 hours?",
        "The function f(x) = 240(1.06)^x models a savings account balance after x years. Interpret the values 240 and 1.06 in context.",
      ],
      isVerifiable: true,
      order: 23,
      nineWeeks: 3,
    },
    {
      id: "a1.sq.2",
      tpiCode: "A.12C/A.12D",
      name: "Geometric Sequences",
      description:
        "Identify terms of geometric sequences given in function form using recursive processes, and write a formula for the nth term given several terms. Connect the common ratio to the base of an exponential function.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 2,
      prerequisites: ["a1.sq.1", "a1.ex.1"],
      sampleProblems: [
        "Find the first four terms of the sequence defined by a(1) = 3 and a(n) = 2 * a(n-1) for n >= 2.",
        "Write a formula for the nth term of the geometric sequence 4, 12, 36, 108, ... Then find a(7).",
        "A ball is dropped from 64 inches and rebounds to 3/4 of its previous height on each bounce. Write a formula for the height after the nth bounce.",
      ],
      isVerifiable: true,
      order: 24,
      nineWeeks: 3,
    },

    // ─── Strand 8: Polynomials & Factoring (TEKS A.10) ───────────────────
    {
      id: "a1.po.1",
      tpiCode: "A.10A",
      name: "Adding and Subtracting Polynomials",
      description:
        "Add and subtract polynomials of degree one and degree two. Combine like terms, distribute the negative when subtracting, and write results in standard form.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 1,
      prerequisites: ["a1.le.1"],
      sampleProblems: [
        "Simplify: (3x^2 + 5x - 4) + (2x^2 - 7x + 9).",
        "Simplify: (6x^2 - 2x + 1) - (4x^2 + 3x - 8).",
        "Subtract (5x - 7) from (x^2 + 2x + 3).",
      ],
      isVerifiable: true,
      order: 25,
      nineWeeks: 3,
    },
    {
      id: "a1.po.2",
      tpiCode: "A.10B/A.10C",
      name: "Multiplying and Dividing Polynomials",
      description:
        "Multiply polynomials of degree one and degree two using the distributive property, including binomial products and the special products (a + b)^2, (a - b)^2, and (a + b)(a - b). Determine the quotient when a polynomial of degree one or two is divided by a polynomial of equal or lesser degree.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 2,
      prerequisites: ["a1.po.1", "a1.ex.1"],
      sampleProblems: [
        "Multiply: (x + 5)(x - 3).",
        "Expand the special product: (2x - 7)^2.",
        "Divide: (x^2 + 9x + 20) / (x + 4).",
      ],
      isVerifiable: true,
      order: 26,
      nineWeeks: 3,
    },
    {
      id: "a1.po.3",
      tpiCode: "A.10D",
      name: "Factoring Out the Greatest Common Factor",
      description:
        "Rewrite polynomial expressions of degree one and degree two in equivalent forms using the distributive property, including factoring out the greatest common factor. Recognize a common binomial factor.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 1,
      prerequisites: ["a1.po.2"],
      sampleProblems: [
        "Factor: 12x^3 + 18x^2.",
        "Factor: 5x^2 - 35x + 10.",
        "Rewrite 4x(x + 3) - 5(x + 3) as a product of two binomials.",
      ],
      isVerifiable: true,
      order: 27,
      nineWeeks: 3,
    },
    {
      id: "a1.po.4",
      tpiCode: "A.10E",
      name: "Factoring Trinomials",
      description:
        "Factor trinomials with real factors in the form ax^2 + bx + c, including perfect square trinomials of degree two. Begin with a = 1, extend to a > 1, and always check by multiplying the factors back together.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 3,
      prerequisites: ["a1.po.3"],
      sampleProblems: [
        "Factor: x^2 + 9x + 20.",
        "Factor: 2x^2 + 11x + 12.",
        "Factor the perfect square trinomial: x^2 - 12x + 36.",
      ],
      isVerifiable: true,
      order: 28,
      nineWeeks: 3,
    },
    {
      id: "a1.po.5",
      tpiCode: "A.10F",
      name: "Difference of Two Squares",
      description:
        "Decide whether a binomial can be written as the difference of two squares, and if possible, use the structure a^2 - b^2 = (a + b)(a - b) to factor it. Combine with GCF factoring to factor completely.",
      gradeLevel: 9,
      strand: "Exponential Functions & Polynomials",
      difficulty: 2,
      prerequisites: ["a1.po.3"],
      sampleProblems: [
        "Factor: x^2 - 49.",
        "Factor: 9x^2 - 25.",
        "Can x^2 + 16 be written as a difference of two squares? Explain. Then factor 3x^2 - 48 completely.",
      ],
      isVerifiable: true,
      order: 29,
      nineWeeks: 3,
    },

    // ─── Strand 9: Quadratic Functions & Equations (TEKS A.6–A.8, A.11A) ─
    {
      id: "a1.qd.1",
      tpiCode: "A.6A/A.7A",
      name: "Graphing Quadratic Functions and Key Attributes",
      description:
        "Graph quadratic functions on the coordinate plane and use the graph to identify key attributes, including the x-intercepts, y-intercept, zeros, vertex, maximum or minimum value, and the equation of the axis of symmetry. Determine the domain and range and represent them using inequalities.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 2,
      prerequisites: ["a1.lf.2", "a1.po.1"],
      sampleProblems: [
        "Graph f(x) = x^2 - 4x + 3. Identify the vertex, axis of symmetry, x-intercepts, and y-intercept.",
        "Does f(x) = -x^2 + 6x - 5 have a maximum or a minimum value? Find it.",
        "State the domain and range of f(x) = x^2 - 4x + 3 using inequalities.",
      ],
      isVerifiable: true,
      order: 30,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.qd.2",
      tpiCode: "A.7C",
      name: "Transformations of the Quadratic Parent Function",
      description:
        "Determine the effects on the graph of the parent function f(x) = x^2 when f(x) is replaced by af(x), f(x) + d, f(x - c), and f(bx) for specific values of a, b, c, and d. Describe shifts, stretches, compressions, and reflections, and write equations for transformed parabolas.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 2,
      prerequisites: ["a1.qd.1", "a1.lf.6"],
      sampleProblems: [
        "Describe how the graph of g(x) = (x - 3)^2 + 2 compares to the parent function f(x) = x^2.",
        "How does the graph of g(x) = -2x^2 differ from f(x) = x^2? Sketch both on the same coordinate plane.",
        "Write the equation of the parabola formed when f(x) = x^2 is shifted 4 units left and 5 units down.",
      ],
      isVerifiable: true,
      order: 31,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.qd.3",
      tpiCode: "A.6B/A.6C",
      name: "Vertex Form and Writing Quadratic Functions",
      description:
        "Write equations of quadratic functions given the vertex and another point on the graph, write the equation in vertex form f(x) = a(x - h)^2 + k, and rewrite from vertex form to standard form f(x) = ax^2 + bx + c. Write quadratic functions given real solutions or graphs of their related equations.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 3,
      prerequisites: ["a1.qd.2"],
      sampleProblems: [
        "A parabola has vertex (2, -3) and passes through (4, 5). Write its equation in vertex form.",
        "Rewrite f(x) = (x + 1)^2 - 9 in standard form.",
        "Write a quadratic function whose zeros are x = -2 and x = 5.",
      ],
      isVerifiable: true,
      order: 32,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "a1.rd.1",
      tpiCode: "A.11A",
      name: "Simplifying Radical Expressions",
      description:
        "Simplify numerical radical expressions involving square roots by factoring out perfect squares. Add, subtract, multiply, and divide square-root expressions, writing answers in simplest radical form.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 2,
      prerequisites: ["8.rn.2"],
      sampleProblems: [
        "Simplify: sqrt(72).",
        "Simplify: sqrt(12) + sqrt(27).",
        "Simplify: sqrt(5) * sqrt(20) and sqrt(48) / sqrt(3).",
      ],
      isVerifiable: true,
      order: 33,
      nineWeeks: 4,
    },
    {
      id: "a1.qd.4",
      tpiCode: "A.7B/A.8A",
      name: "Solving Quadratics by Factoring and Square Roots",
      description:
        "Solve quadratic equations having real solutions by factoring with the zero product property and by taking square roots. Describe the relationship between the linear factors of a quadratic expression and the zeros of its associated quadratic function.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 2,
      prerequisites: ["a1.po.4", "a1.po.5", "a1.rd.1"],
      sampleProblems: [
        "Solve by factoring: x^2 + 5x - 24 = 0.",
        "Solve by taking square roots: 3x^2 - 48 = 0.",
        "The function f(x) = x^2 - 6x + 8 factors as (x - 2)(x - 4). What are the zeros of f, and what do they represent on the graph?",
      ],
      isVerifiable: true,
      order: 34,
      nineWeeks: 4,
    },
    {
      id: "a1.qd.5",
      tpiCode: "A.8A",
      name: "Completing the Square",
      description:
        "Solve quadratic equations having real solutions by completing the square, including equations whose solutions are irrational. Use completing the square to rewrite a quadratic function in vertex form and identify the vertex.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 3,
      prerequisites: ["a1.qd.4", "a1.qd.3"],
      sampleProblems: [
        "Solve by completing the square: x^2 + 6x - 7 = 0.",
        "Solve by completing the square: x^2 - 10x + 13 = 0. Give exact answers in simplified radical form.",
        "Rewrite f(x) = x^2 + 8x + 11 in vertex form by completing the square, and state the vertex.",
      ],
      isVerifiable: true,
      order: 35,
      nineWeeks: 4,
    },
    {
      id: "a1.qd.6",
      tpiCode: "A.8A",
      name: "The Quadratic Formula",
      description:
        "Solve quadratic equations having real solutions by applying the quadratic formula x = (-b +/- sqrt(b^2 - 4ac)) / (2a). Use the discriminant b^2 - 4ac to determine the number of real solutions, and give exact answers in simplified radical form.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 3,
      prerequisites: ["a1.qd.5", "a1.rd.1"],
      sampleProblems: [
        "Solve using the quadratic formula: 2x^2 - 7x + 3 = 0.",
        "Solve x^2 + 4x - 9 = 0. Give exact answers in simplified radical form.",
        "Use the discriminant to determine how many real solutions 3x^2 + 2x + 5 = 0 has.",
      ],
      isVerifiable: true,
      order: 36,
      nineWeeks: 4,
    },
    {
      id: "a1.qd.7",
      tpiCode: "A.8A/A.8B",
      name: "Quadratic Applications and Modeling",
      description:
        "Solve real-world problems modeled by quadratic equations, including projectile motion, area, and revenue situations. Write quadratic functions that provide a reasonable fit to data to estimate solutions and make predictions, choosing the most efficient solving method.",
      gradeLevel: 9,
      strand: "Quadratic Functions",
      difficulty: 3,
      prerequisites: ["a1.qd.4", "a1.qd.6"],
      sampleProblems: [
        "A ball is launched so its height in feet after t seconds is h(t) = -16t^2 + 48t + 64. When does the ball hit the ground?",
        "A rectangular garden's length is 3 feet more than its width, and its area is 70 square feet. Find the dimensions.",
        "A rocket's height follows the table t: 0, 1, 2, 3 and h: 0, 48, 64, 48, which fits h(t) = -16t^2 + 64t. Use the model to predict when the height is 0 again.",
      ],
      isVerifiable: true,
      order: 37,
      nineWeeks: 4,
    },

    // ─── Strand 10: Choosing Models (TEKS A.4C, A.8B, A.9E) ──────────────
    {
      id: "a1.md.1",
      tpiCode: "A.4C/A.8B/A.9E",
      name: "Choosing Linear, Quadratic, or Exponential Models",
      description:
        "Decide whether a linear, quadratic, or exponential function best models a data set or situation by examining first differences, second differences, and common ratios over equal intervals. Write the chosen model and use it to make predictions.",
      gradeLevel: 9,
      strand: "Data & Statistics",
      difficulty: 3,
      prerequisites: ["a1.dt.2", "a1.ex.3", "a1.qd.7"],
      sampleProblems: [
        "For the table x: 0, 1, 2, 3 and y: 5, 10, 20, 40, decide whether a linear, quadratic, or exponential model fits best. Justify using differences or ratios, then write the model.",
        "For the table x: 0, 1, 2, 3 and y: 3, 5, 7, 9, choose the best model type and write the function.",
        "A data set has constant second differences over equal x-intervals. What type of function models it? Explain how you know.",
      ],
      isVerifiable: true,
      order: 38,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'table',
    },
  ],
};
