import { GradeCurriculum } from '../../../types';

// Texas TEKS Geometry (TAC 111.41). The G.1 mathematical process standards are
// embedded throughout every topic rather than listed separately.
export const grade10GeometryCurriculum: GradeCurriculum = {
  grade: 10,
  label: "Geometry (Honors)",
  topics: [
    // ─── Strand 1: Foundations & Proof (TEKS G.2, G.4, G.5, G.6A) ────────
    {
      id: "geo.fo.1",
      tpiCode: "G.4A",
      name: "Undefined Terms, Points, Lines, and Planes",
      description:
        "Distinguish between undefined terms (point, line, plane), definitions, postulates, conjectures, and theorems. Name and sketch points, lines, segments, rays, and planes using correct geometric notation.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 1,
      prerequisites: [],
      sampleProblems: [
        "Points A, B, and C lie on line m, and point D is not on line m. Name three rays shown in the figure and identify a set of three collinear points.",
        "Classify each statement as an undefined term, definition, postulate, or theorem: (a) Through any two points there is exactly one line. (b) A right angle is an angle that measures 90 degrees. (c) point.",
        "Draw and label plane P containing points A and B, with line AB in the plane and point C not in plane P.",
      ],
      isVerifiable: true,
      order: 1,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.fo.2",
      tpiCode: "G.2A/G.2B",
      name: "Distance, Midpoint, and Fractional Distance on the Coordinate Plane",
      description:
        "Derive and use the distance and midpoint formulas on the coordinate plane. Determine the coordinates of a point that is a given fractional distance less than one from one endpoint of a segment to the other, including the midpoint.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 1,
      prerequisites: ["geo.fo.1", "8.py.3"],
      sampleProblems: [
        "Find the distance between A(-3, 4) and B(5, -2). Give the exact answer in simplest radical form.",
        "Find the midpoint of the segment with endpoints (2, -7) and (8, 3).",
        "Point P is 1/4 of the distance from A(0, 0) to B(8, 12). Find the coordinates of P.",
      ],
      isVerifiable: true,
      order: 2,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "geo.fo.3",
      tpiCode: "G.2B/G.2C",
      name: "Slope, Parallel, and Perpendicular Lines",
      description:
        "Use slope to verify geometric relationships on the coordinate plane, including parallelism, perpendicularity, and right angles in figures. Determine the equation of a line parallel or perpendicular to a given line that passes through a given point.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 2,
      prerequisites: ["geo.fo.2", "8.sl.9"],
      sampleProblems: [
        "Line 1 passes through (1, 2) and (4, 8); line 2 passes through (0, 5) and (6, 2). Are the lines parallel, perpendicular, or neither? Justify using slopes.",
        "Write the equation of the line through (3, -1) that is perpendicular to y = (1/2)x + 4.",
        "Triangle ABC has vertices A(0, 0), B(4, 2), and C(2, 6). Use slopes to show that triangle ABC has a right angle at B.",
      ],
      isVerifiable: true,
      order: 3,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "geo.fo.4",
      tpiCode: "G.5B/G.5C",
      name: "Compass and Straightedge Constructions",
      description:
        "Construct congruent segments, congruent angles, segment bisectors, angle bisectors, perpendicular lines, perpendicular bisectors, and a line parallel to a given line through a point not on the line, using only a compass and straightedge. Use constructions to make conjectures about geometric relationships.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 2,
      prerequisites: ["geo.fo.1"],
      sampleProblems: [
        "Construct the perpendicular bisector of a 6 cm segment AB. Describe each arc you draw and explain why the result is perpendicular to AB at its midpoint.",
        "Given angle ABC, construct its bisector with a compass and straightedge, then explain how the construction guarantees two congruent angles.",
        "Construct a line parallel to line m through point P not on m by copying a corresponding angle along a transversal.",
      ],
      isVerifiable: false,
      order: 4,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.fo.5",
      tpiCode: "G.4B/G.4C",
      name: "Conditional Statements, Converses, and Counterexamples",
      description:
        "Identify the hypothesis and conclusion of a conditional statement and write its converse, inverse, and contrapositive, determining the validity of each. Recognize that a biconditional is a true conditional with a true converse, and verify that a conjecture is false using a counterexample.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 2,
      prerequisites: ["geo.fo.1"],
      sampleProblems: [
        "Write the converse, inverse, and contrapositive of: 'If a figure is a square, then it has four right angles.' State whether each new statement is true or false.",
        "Find a counterexample that shows the conjecture is false: 'If a number is divisible by 3, then it is odd.'",
        "The conditional 'If an angle is a right angle, then it measures 90 degrees' is true. Is its converse true? If so, write the statement as a biconditional.",
      ],
      isVerifiable: true,
      order: 5,
      nineWeeks: 1,
    },
    {
      id: "geo.fo.6",
      tpiCode: "G.6A",
      name: "Angle Pair Relationships",
      description:
        "Identify and use vertical angles, linear pairs, complementary angles, and supplementary angles formed by intersecting lines to find unknown angle measures. Set up and solve equations based on these angle relationships.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 1,
      prerequisites: ["geo.fo.1", "8.ag.1"],
      sampleProblems: [
        "Two lines intersect so that one of the angles formed measures 37 degrees. Find the measures of the other three angles and name the relationship each has with the 37-degree angle.",
        "Angle A = (3x + 2) degrees and angle B = (2x - 7) degrees are complementary. Find x and the measure of each angle.",
        "Angles 1 and 2 form a linear pair. If angle 1 = (5x - 10) degrees and angle 2 = (3x + 30) degrees, find the measure of each angle.",
      ],
      isVerifiable: true,
      order: 6,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'angle',
    },
    {
      id: "geo.fo.7",
      tpiCode: "G.5A/G.6A",
      name: "Parallel Lines and Transversals",
      description:
        "Investigate patterns and verify theorems about the angles formed when parallel lines are cut by a transversal, including corresponding, alternate interior, alternate exterior, and same-side interior angles. Use these relationships and their converses to find unknown angles and to show that lines are parallel.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 2,
      prerequisites: ["geo.fo.6", "8.ag.1"],
      sampleProblems: [
        "Parallel lines p and q are cut by transversal t, and one angle measures 112 degrees. Find the measures of all eight angles, naming the angle pair relationship that justifies each.",
        "Lines a and b are cut by a transversal so that alternate interior angles measure (4x + 10) degrees and (6x - 20) degrees. For what value of x are lines a and b parallel?",
        "In the figure, line m is parallel to line n, and same-side interior angles measure (2x + 35) degrees and (3x + 25) degrees. Find x and the measure of each angle.",
      ],
      isVerifiable: true,
      order: 7,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.fo.8",
      tpiCode: "G.6A/G.4A",
      name: "Introduction to Proof",
      description:
        "Write two-column and paragraph proofs about segments and angles, including the Vertical Angles Theorem and the proof that points on the perpendicular bisector of a segment are equidistant from its endpoints. Justify each statement with a definition, postulate, property, or previously proven theorem.",
      gradeLevel: 10,
      strand: "Foundations & Proof",
      difficulty: 3,
      prerequisites: ["geo.fo.5", "geo.fo.7"],
      sampleProblems: [
        "Write a two-column proof: Given that angle 1 and angle 2 are vertical angles, prove that angle 1 is congruent to angle 2.",
        "Given: M is the midpoint of segment AB and AB = 24. Prove: AM = 12. Supply a reason for each statement.",
        "Point P lies on the perpendicular bisector of segment AB. Write a paragraph proof that PA = PB.",
      ],
      isVerifiable: false,
      order: 8,
      nineWeeks: 1,
      requiresImage: true,
      imageType: 'geometric-figure',
    },

    // ─── Strand 2: Transformations & Congruence (TEKS G.3, G.6B–D, G.5D, G.4D) ──
    {
      id: "geo.tr.1",
      tpiCode: "G.3A/G.3D",
      name: "Rigid Transformations and Symmetry",
      description:
        "Describe and perform translations, reflections, and rotations of figures in the plane using coordinate notation such as (x, y) -> (x + a, y + b). Identify and distinguish between reflectional and rotational symmetry in plane figures.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 1,
      prerequisites: ["8.tr.1", "8.tr.2", "8.tr.3"],
      sampleProblems: [
        "Triangle ABC has vertices A(1, 2), B(4, 2), and C(4, 6). Write the coordinate rule for a reflection across the y-axis and give the image vertices.",
        "Rotate the quadrilateral with vertices (2, 1), (5, 1), (5, 3), (2, 3) by 90 degrees counterclockwise about the origin using coordinate notation. List the image vertices.",
        "How many lines of symmetry does a regular hexagon have, and what is its smallest angle of rotational symmetry?",
      ],
      isVerifiable: true,
      order: 9,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "geo.tr.2",
      tpiCode: "G.3B/G.3C",
      name: "Compositions and Sequences of Transformations",
      description:
        "Determine the image or pre-image of a figure under a composition of rigid transformations, a composition of non-rigid transformations (dilations), or a composition of both. Identify a sequence of transformations that carries a given pre-image onto a given image.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 2,
      prerequisites: ["geo.tr.1", "8.dl.1"],
      sampleProblems: [
        "Triangle PQR has vertices P(1, 1), Q(3, 1), and R(1, 4). Reflect it across the x-axis, then translate using (x, y) -> (x + 5, y - 2). Give the final image vertices.",
        "A segment with endpoints (2, 4) and (6, 8) is dilated by scale factor 1/2 centered at the origin and then rotated 180 degrees about the origin. Find the final endpoints.",
        "Triangle ABC with A(1, 1), B(3, 1), C(1, 4) is mapped onto A'(4, -1), B'(6, -1), C'(4, -4). Identify a sequence of two transformations that carries ABC onto its image.",
      ],
      isVerifiable: true,
      order: 10,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "geo.cg.1",
      tpiCode: "G.6C",
      name: "Congruence Through Rigid Motions",
      description:
        "Apply the definition of congruence in terms of rigid transformations: two figures are congruent if and only if a sequence of rigid motions maps one onto the other. Identify congruent figures and name their corresponding sides and angles.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 2,
      prerequisites: ["geo.tr.2"],
      sampleProblems: [
        "Triangle ABC is rotated 90 degrees clockwise about the origin to form triangle DEF. Explain why triangle DEF is congruent to triangle ABC, and name the corresponding sides and angles.",
        "Quadrilateral JKLM has vertices J(0, 0), K(3, 0), L(3, 2), M(0, 2), and quadrilateral WXYZ has vertices W(1, -1), X(4, -1), Y(4, -3), Z(1, -3). Describe a sequence of rigid motions that shows the quadrilaterals are congruent.",
        "Triangle A'B'C' is the image of triangle ABC under a dilation with scale factor 2. Explain why this transformation does NOT show the triangles are congruent.",
      ],
      isVerifiable: true,
      order: 11,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "geo.cg.2",
      tpiCode: "G.5A/G.6B",
      name: "Triangle Congruence Criteria: SSS, SAS, ASA, AAS, HL",
      description:
        "Investigate the minimum criteria required to guarantee triangle congruence and identify whether two triangles are congruent by SSS, SAS, ASA, AAS, or HL. Mark diagrams and write congruence statements with vertices in corresponding order.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 2,
      prerequisites: ["geo.cg.1"],
      sampleProblems: [
        "In triangles ABC and DEF, AB = DE, BC = EF, and angle B is congruent to angle E. Which congruence criterion applies? Write the congruence statement.",
        "Two right triangles have congruent hypotenuses and one pair of congruent legs. Which criterion proves the triangles congruent?",
        "In the figure, triangles ABC and ADC share side AC, with AB = AD and angle BAC congruent to angle DAC. Are the triangles congruent? Name the criterion.",
      ],
      isVerifiable: true,
      order: 12,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.cg.3",
      tpiCode: "G.6B",
      name: "Triangle Congruence Proofs",
      description:
        "Prove two triangles congruent by applying the SSS, SAS, ASA, AAS, and HL congruence conditions in two-column or paragraph form. Use CPCTC (corresponding parts of congruent triangles are congruent) to prove additional segment and angle relationships.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 3,
      prerequisites: ["geo.cg.2", "geo.fo.8"],
      sampleProblems: [
        "Given: C is the midpoint of both segment AE and segment BD. Prove: triangle ACB is congruent to triangle ECD.",
        "Given: segment PS is congruent to segment RS, and segment SQ bisects angle PSR. Prove: triangle PSQ is congruent to triangle RSQ, then use CPCTC to show PQ = RQ.",
        "Given: in quadrilateral ABCD, AB = CD and AD = CB. Prove: triangle ABD is congruent to triangle CDB.",
      ],
      isVerifiable: false,
      order: 13,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.cg.4",
      tpiCode: "G.6D/G.4D",
      name: "Triangle Angle Sum and Exterior Angles",
      description:
        "Verify and apply the Triangle Angle Sum Theorem and the Exterior Angle Theorem to find unknown angle measures. Compare geometric relationships between Euclidean and spherical geometries, including parallel lines and the sum of the angles of a triangle on a sphere.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 2,
      prerequisites: ["geo.fo.7", "8.ag.1"],
      sampleProblems: [
        "In triangle ABC, angle A = (2x + 10) degrees, angle B = (3x - 5) degrees, and angle C = 40 degrees. Find x and the measure of each angle.",
        "An exterior angle of a triangle measures 125 degrees, and one remote interior angle measures 68 degrees. Find the other remote interior angle.",
        "On a sphere, a triangle is formed by the equator and two lines of longitude that meet at the north pole at a 90-degree angle. What is the angle sum of this triangle, and how does it compare to the angle sum of a triangle in the Euclidean plane?",
      ],
      isVerifiable: true,
      order: 14,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.cg.5",
      tpiCode: "G.6D/G.5D",
      name: "Isosceles and Equilateral Triangles; Triangle Inequalities",
      description:
        "Apply the Base Angles Theorem and its converse for isosceles triangles and the properties of equilateral triangles. Verify the Triangle Inequality Theorem using constructions and apply it, along with the relationship between side lengths and opposite angles, to solve problems.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 2,
      prerequisites: ["geo.cg.4"],
      sampleProblems: [
        "In isosceles triangle ABC, AB = AC and vertex angle A measures 44 degrees. Find the measures of the base angles.",
        "Can a triangle have side lengths 4, 9, and 14? Justify your answer using the Triangle Inequality Theorem.",
        "Two sides of a triangle measure 8 and 13. Write an inequality describing all possible lengths x of the third side.",
      ],
      isVerifiable: true,
      order: 15,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.cg.6",
      tpiCode: "G.6D/G.5A",
      name: "Midsegments, Special Segments, and Points of Concurrency",
      description:
        "Apply the Triangle Midsegment Theorem and the properties of medians, altitudes, perpendicular bisectors, and angle bisectors of triangles. Identify the centroid, circumcenter, incenter, and orthocenter, and use concurrency relationships such as the centroid dividing each median in a 2:1 ratio.",
      gradeLevel: 10,
      strand: "Transformations & Congruence",
      difficulty: 3,
      prerequisites: ["geo.cg.5", "geo.fo.2"],
      sampleProblems: [
        "Segment DE is a midsegment of triangle ABC parallel to side BC. If BC = 18, find DE. If instead DE = x + 3 and BC = 4x - 2, find x.",
        "In triangle PQR, the medians intersect at centroid G. If median PM = 15, find PG and GM.",
        "Which point of concurrency is equidistant from the three vertices of a triangle, and which is equidistant from the three sides? Explain how each point is constructed.",
      ],
      isVerifiable: true,
      order: 16,
      nineWeeks: 2,
      requiresImage: true,
      imageType: 'geometric-figure',
    },

    // ─── Strand 3: Similarity & Right Triangles (TEKS G.7, G.8, G.9) ─────
    {
      id: "geo.si.1",
      tpiCode: "G.7A",
      name: "Dilations and Similar Figures",
      description:
        "Apply the definition of similarity in terms of a dilation: similar figures have congruent corresponding angles and proportional corresponding sides. Perform dilations on the coordinate plane and identify the scale factor between similar figures.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 2,
      prerequisites: ["8.dl.1", "geo.tr.2"],
      sampleProblems: [
        "Dilate triangle ABC with vertices A(2, 2), B(6, 2), C(2, 8) by scale factor 3/2 centered at the origin. Give the image vertices.",
        "Rectangle 1 has sides 6 and 9; rectangle 2 has sides 10 and 15. Are the rectangles similar? If so, state the scale factor.",
        "Triangle DEF is the image of triangle ABC under a dilation with scale factor 4. If AB = 7 and angle A = 52 degrees, find DE and the measure of angle D.",
      ],
      isVerifiable: true,
      order: 17,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },
    {
      id: "geo.si.2",
      tpiCode: "G.7B",
      name: "Triangle Similarity: AA, SSS, SAS",
      description:
        "Apply the Angle-Angle criterion, along with the SSS and SAS similarity conditions, to verify that two triangles are similar. Use the proportionality of corresponding sides of similar triangles to find unknown lengths, including indirect measurement problems.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 2,
      prerequisites: ["geo.si.1", "geo.cg.4"],
      sampleProblems: [
        "Triangle ABC has angles measuring 38 and 71 degrees; triangle XYZ has angles measuring 71 and 71 degrees. Are the triangles similar by AA? Justify.",
        "Triangles PQR and STU have PQ/ST = QR/TU = 3/5, and included angles Q and T each measure 64 degrees. Are the triangles similar? By which criterion?",
        "A 5-ft student casts an 8-ft shadow at the same time a flagpole casts a 32-ft shadow. Use similar triangles to find the height of the flagpole.",
      ],
      isVerifiable: true,
      order: 18,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.si.3",
      tpiCode: "G.8A",
      name: "Triangle Proportionality Theorems",
      description:
        "Prove and apply theorems about similar triangles, including the Triangle Proportionality Theorem (a line parallel to one side of a triangle divides the other two sides proportionally) and its converse. Use proportional segments created by parallel lines cutting transversals to solve problems.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 3,
      prerequisites: ["geo.si.2"],
      sampleProblems: [
        "In triangle ABC, segment DE is parallel to side BC, with D on AB and E on AC. If AD = 6, DB = 9, and AE = 8, find EC.",
        "Three parallel lines cut two transversals into segments of lengths 4 and 10 on the first transversal and x and 15 on the second. Find x.",
        "In triangle ABC, D lies on AB and E lies on AC with AD = 5, DB = 10, AE = 4, and EC = 8. Is DE parallel to BC? Justify using the converse of the Triangle Proportionality Theorem.",
      ],
      isVerifiable: true,
      order: 19,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.rt.1",
      tpiCode: "G.9B",
      name: "Pythagorean Theorem, Converse, and Pythagorean Triples",
      description:
        "Apply the Pythagorean Theorem and its converse, including recognizing Pythagorean triples such as 3-4-5, 5-12-13, and 8-15-17, to find missing side lengths and to classify triangles as acute, right, or obtuse.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 1,
      prerequisites: ["8.py.2", "8.py.3"],
      sampleProblems: [
        "A right triangle has legs of 9 and 12. Use a Pythagorean triple to find the hypotenuse without a calculator.",
        "Find the missing leg of a right triangle with hypotenuse 17 and one leg of length 8.",
        "Classify the triangle with side lengths 7, 9, and 12 as acute, right, or obtuse using the converse of the Pythagorean Theorem.",
      ],
      isVerifiable: true,
      order: 20,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.rt.2",
      tpiCode: "G.8B",
      name: "Geometric Mean in Right Triangles",
      description:
        "Identify the three similar triangles formed when an altitude is drawn to the hypotenuse of a right triangle. Apply the geometric mean relationships for the altitude and for each leg to find unknown segment lengths.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 3,
      prerequisites: ["geo.si.2", "geo.rt.1"],
      sampleProblems: [
        "Find the geometric mean of 4 and 25.",
        "In right triangle ABC, the altitude from the right angle at C meets hypotenuse AB at D, with AD = 4 and DB = 9. Find the length of altitude CD.",
        "The altitude to the hypotenuse divides the hypotenuse into segments of lengths 3 and 12. Find the length of the leg adjacent to the segment of length 3, in simplest radical form.",
      ],
      isVerifiable: true,
      order: 21,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.rt.3",
      tpiCode: "G.9B",
      name: "Special Right Triangles: 45-45-90 and 30-60-90",
      description:
        "Apply the side relationships in 45-45-90 triangles (legs congruent, hypotenuse = leg * sqrt(2)) and 30-60-90 triangles (hypotenuse = 2 * short leg, long leg = short leg * sqrt(3)) to find exact side lengths.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 2,
      prerequisites: ["geo.rt.1"],
      sampleProblems: [
        "A 45-45-90 triangle has a leg of length 8. Find the hypotenuse in simplest radical form.",
        "A 30-60-90 triangle has a hypotenuse of 14. Find the lengths of both legs.",
        "A square has a diagonal of length 10*sqrt(2). Find the side length and the perimeter of the square.",
      ],
      isVerifiable: true,
      order: 22,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.rt.4",
      tpiCode: "G.9A",
      name: "Trigonometric Ratios and Applications",
      description:
        "Determine side lengths and angle measures in right triangles using the sine, cosine, and tangent ratios, including inverse trigonometric functions. Solve real-world problems involving angles of elevation and depression.",
      gradeLevel: 10,
      strand: "Similarity & Right Triangles",
      difficulty: 3,
      prerequisites: ["geo.rt.3", "geo.si.2"],
      sampleProblems: [
        "In right triangle ABC with the right angle at C, angle A = 34 degrees and hypotenuse AB = 20. Find BC to the nearest tenth.",
        "A ladder reaches 15 ft up a wall with its base 6 ft from the wall. Find the angle the ladder makes with the ground, to the nearest degree.",
        "From a point 80 ft from the base of a tower, the angle of elevation to the top is 52 degrees. Find the height of the tower to the nearest foot.",
      ],
      isVerifiable: true,
      order: 23,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },

    // ─── Strand 4: Polygons & Quadrilaterals (TEKS G.5A, G.6E, G.2B) ─────
    {
      id: "geo.qd.1",
      tpiCode: "G.5A",
      name: "Interior and Exterior Angles of Polygons",
      description:
        "Investigate and apply the formula for the sum of the interior angles of a polygon, (n - 2) * 180 degrees, and the fact that the exterior angles of any polygon sum to 360 degrees. Find individual angle measures in regular polygons and unknown angles in irregular polygons.",
      gradeLevel: 10,
      strand: "Polygons & Quadrilaterals",
      difficulty: 1,
      prerequisites: ["geo.cg.4"],
      sampleProblems: [
        "Find the sum of the interior angles of a decagon.",
        "Each interior angle of a regular polygon measures 150 degrees. How many sides does the polygon have?",
        "Four angles of a pentagon measure 100, 96, 114, and 82 degrees. Find the measure of the fifth angle.",
      ],
      isVerifiable: true,
      order: 24,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.qd.2",
      tpiCode: "G.6E/G.5A",
      name: "Parallelogram Properties and Proofs",
      description:
        "Apply the properties of parallelograms: opposite sides congruent, opposite angles congruent, consecutive angles supplementary, and diagonals that bisect each other. Prove that a quadrilateral is a parallelogram using sides, angles, or diagonals, including coordinate methods.",
      gradeLevel: 10,
      strand: "Polygons & Quadrilaterals",
      difficulty: 2,
      prerequisites: ["geo.fo.7", "geo.qd.1"],
      sampleProblems: [
        "In parallelogram ABCD, AB = 3x + 4 and CD = 5x - 8. Find x and the length of AB.",
        "In parallelogram PQRS, angle P = (2y + 15) degrees and angle Q = (3y - 10) degrees. Find y and the measure of each angle.",
        "Quadrilateral ABCD has vertices A(0, 0), B(5, 1), C(7, 5), and D(2, 4). Use slopes or the midpoints of the diagonals to determine whether ABCD is a parallelogram.",
      ],
      isVerifiable: true,
      order: 25,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.qd.3",
      tpiCode: "G.6E",
      name: "Rectangles, Rhombi, and Squares",
      description:
        "Apply the special properties of rectangles (congruent diagonals), rhombi (perpendicular diagonals that bisect the vertex angles), and squares. Classify a parallelogram as a rectangle, rhombus, or square and justify the classification using sides, angles, or diagonals.",
      gradeLevel: 10,
      strand: "Polygons & Quadrilaterals",
      difficulty: 2,
      prerequisites: ["geo.qd.2", "geo.rt.1"],
      sampleProblems: [
        "In rectangle ABCD, diagonal AC = 4x - 6 and diagonal BD = 2x + 10. Find x and the length of each diagonal.",
        "The diagonals of rhombus PQRS measure 12 and 16. Find the side length of the rhombus.",
        "A parallelogram has four congruent sides and one right angle. What is the most specific classification of the quadrilateral? Justify your answer.",
      ],
      isVerifiable: true,
      order: 26,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.qd.4",
      tpiCode: "G.5A",
      name: "Trapezoids and Kites",
      description:
        "Apply the properties of trapezoids, including the base angles of isosceles trapezoids and the midsegment whose length is the average of the two bases, and the properties of kites, including perpendicular diagonals and one pair of congruent opposite angles.",
      gradeLevel: 10,
      strand: "Polygons & Quadrilaterals",
      difficulty: 2,
      prerequisites: ["geo.qd.1", "geo.rt.1"],
      sampleProblems: [
        "The bases of a trapezoid measure 10 and 18. Find the length of the midsegment.",
        "In isosceles trapezoid ABCD with parallel bases AB and CD, angle A measures 72 degrees. Find the measures of the other three angles.",
        "The diagonals of kite WXYZ intersect at P. If WP = 6 and XP = 8, find the length of side WX.",
      ],
      isVerifiable: true,
      order: 27,
      nineWeeks: 3,
      requiresImage: true,
      imageType: 'geometric-figure',
    },

    // ─── Strand 5: Circles (TEKS G.12) ───────────────────────────────────
    {
      id: "geo.ci.1",
      tpiCode: "G.12A",
      name: "Central and Inscribed Angles, Arcs, and Chords",
      description:
        "Apply relationships among central angles, inscribed angles, arcs, and chords: a central angle equals its intercepted arc, an inscribed angle is half its intercepted arc, an angle inscribed in a semicircle is a right angle, and opposite angles of an inscribed quadrilateral are supplementary.",
      gradeLevel: 10,
      strand: "Circles",
      difficulty: 2,
      prerequisites: ["geo.fo.6", "geo.qd.1"],
      sampleProblems: [
        "Central angle AOB of circle O measures 78 degrees. Find the measure of arc AB and of an inscribed angle ACB that intercepts the same arc.",
        "Quadrilateral ABCD is inscribed in a circle, and angle A measures 94 degrees. Find the measure of angle C.",
        "Segment AC is a diameter of a circle, and point B lies on the circle. If angle A of triangle ABC measures 33 degrees, find the measures of angles B and C.",
      ],
      isVerifiable: true,
      order: 28,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.ci.2",
      tpiCode: "G.12A",
      name: "Tangents, Secants, and Segment Relationships in Circles",
      description:
        "Apply theorems involving tangents and secants: a tangent is perpendicular to the radius at the point of tangency, tangent segments from a common external point are congruent, and the angle and segment relationships formed by two chords, two secants, or a tangent and a secant.",
      gradeLevel: 10,
      strand: "Circles",
      difficulty: 3,
      prerequisites: ["geo.ci.1", "geo.rt.1"],
      sampleProblems: [
        "From external point P, tangent segments PA and PB are drawn to circle O. If PA = 5x - 3 and PB = 2x + 9, find x and the length of each tangent segment.",
        "Two chords intersect inside a circle. One chord is divided into segments of lengths 4 and 9; the other into segments of lengths 6 and x. Find x.",
        "A tangent from point P touches a circle at T, and a secant from P intersects the circle at A and then B, with PA = 4 and AB = 12. Find PT.",
      ],
      isVerifiable: true,
      order: 29,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.ci.3",
      tpiCode: "G.12B/G.12C/G.12D",
      name: "Arc Length, Sector Area, and Radian Measure",
      description:
        "Use the proportional relationship between a central angle and the circumference to find arc length, and between a central angle and the circle's area to find sector area. Describe the radian measure of an angle as the ratio of the intercepted arc length to the radius.",
      gradeLevel: 10,
      strand: "Circles",
      difficulty: 2,
      prerequisites: ["geo.ci.1"],
      sampleProblems: [
        "A circle has radius 9 cm. Find the length of an arc intercepted by a central angle of 80 degrees. Give an exact answer in terms of pi.",
        "Find the area of a sector with radius 6 in and central angle 120 degrees, in terms of pi.",
        "An arc of length 5 cm is intercepted by a central angle in a circle of radius 4 cm. Find the radian measure of the central angle.",
      ],
      isVerifiable: true,
      order: 30,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.ci.4",
      tpiCode: "G.12E",
      name: "Equations of Circles",
      description:
        "Show that the equation of a circle centered at the origin with radius r is x^2 + y^2 = r^2, and determine the equation (x - h)^2 + (y - k)^2 = r^2 for a circle with center (h, k) and radius r. Graph circles and identify the center and radius from an equation.",
      gradeLevel: 10,
      strand: "Circles",
      difficulty: 2,
      prerequisites: ["geo.fo.2", "geo.rt.1"],
      sampleProblems: [
        "Write the equation of the circle with center (3, -2) and radius 5.",
        "Identify the center and radius of the circle (x + 4)^2 + (y - 1)^2 = 49, then sketch its graph.",
        "A circle is centered at the origin and passes through the point (6, 8). Write its equation.",
      ],
      isVerifiable: true,
      order: 31,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'coordinate-plane',
    },

    // ─── Strand 6: Measurement & Solids (TEKS G.10, G.11) ────────────────
    {
      id: "geo.ms.1",
      tpiCode: "G.11A/G.11B",
      name: "Area of Regular Polygons and Composite Figures",
      description:
        "Apply the formula A = (1/2) * apothem * perimeter for the area of regular polygons, and determine the area of composite two-dimensional figures made of triangles, parallelograms, trapezoids, kites, regular polygons, and sectors of circles, using appropriate units of measure.",
      gradeLevel: 10,
      strand: "Measurement & Solids",
      difficulty: 2,
      prerequisites: ["geo.rt.3", "geo.rt.4", "geo.ci.3"],
      sampleProblems: [
        "Find the area of a regular hexagon with side length 10 cm. Give an exact answer using sqrt(3).",
        "A composite figure consists of a 12 ft by 8 ft rectangle topped by a semicircle of diameter 8 ft. Find the total area in terms of pi.",
        "Find the area of a regular pentagon with side length 8 in and apothem approximately 5.5 in.",
      ],
      isVerifiable: true,
      order: 32,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'polygon-grid',
    },
    {
      id: "geo.ms.2",
      tpiCode: "G.10B",
      name: "Effects of Dimensional Change",
      description:
        "Determine and describe how proportional and non-proportional changes in the linear dimensions of a shape affect its perimeter, area, surface area, and volume, using the scale factor relationships k, k^2, and k^3.",
      gradeLevel: 10,
      strand: "Measurement & Solids",
      difficulty: 2,
      prerequisites: ["geo.ms.1", "8.vl.1"],
      sampleProblems: [
        "The side lengths of a triangle are tripled. What happens to its perimeter? What happens to its area?",
        "The radius of a cylinder is doubled while its height stays the same. How does the volume change?",
        "A rectangular prism has a volume of 40 cubic inches. Every dimension is scaled by a factor of 3/2. Find the new volume.",
      ],
      isVerifiable: true,
      order: 33,
      nineWeeks: 4,
    },
    {
      id: "geo.ms.3",
      tpiCode: "G.11C/G.11D",
      name: "Surface Area and Volume of Solids",
      description:
        "Apply the formulas for the lateral and total surface area and for the volume of prisms, pyramids, cylinders, cones, spheres, and composite solids, using nets to organize surface area calculations and appropriate units of measure.",
      gradeLevel: 10,
      strand: "Measurement & Solids",
      difficulty: 2,
      prerequisites: ["geo.ms.1", "8.vl.1", "8.vl.2"],
      sampleProblems: [
        "Find the total surface area and the volume of a cylinder with radius 5 cm and height 12 cm, in terms of pi.",
        "A square pyramid has base edge 10 in and slant height 13 in. Find its total surface area; then use its height to find the volume.",
        "A grain silo is a cylinder of radius 6 ft and height 20 ft topped by a hemisphere of the same radius. Find the total volume in terms of pi.",
      ],
      isVerifiable: true,
      order: 34,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'net',
    },
    {
      id: "geo.ms.4",
      tpiCode: "G.10A",
      name: "Cross-Sections and Solids of Revolution",
      description:
        "Identify the shapes of two-dimensional cross-sections created when a plane intersects a prism, pyramid, cylinder, cone, or sphere, and identify the three-dimensional solids generated by rotating a two-dimensional shape about an axis.",
      gradeLevel: 10,
      strand: "Measurement & Solids",
      difficulty: 1,
      prerequisites: ["geo.ms.3"],
      sampleProblems: [
        "A plane slices a right cylinder parallel to its base. What is the shape of the cross-section? What shape results if the plane instead passes through the axis, perpendicular to the base?",
        "Describe the cross-section formed when a plane cuts a square pyramid parallel to its base.",
        "A right triangle is rotated about one of its legs. Name the solid of revolution that is generated.",
      ],
      isVerifiable: true,
      order: 35,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
    },

    // ─── Strand 7: Probability (TEKS G.13) ───────────────────────────────
    {
      id: "geo.pr.1",
      tpiCode: "G.13B",
      name: "Geometric Probability",
      description:
        "Determine probabilities based on area and length: the probability of an event is the ratio of the measure of the favorable region to the measure of the total region. Apply geometric probability to contextual problems such as targets, spinners, and maps.",
      gradeLevel: 10,
      strand: "Probability",
      difficulty: 2,
      prerequisites: ["geo.ms.1"],
      sampleProblems: [
        "A dart lands at random on a square board with side 20 in that contains a circular target of radius 5 in. Find the probability the dart lands inside the circle, in terms of pi and as a decimal.",
        "A point is chosen at random on a segment of length 15. Find the probability that the point lies within 3 units of the left endpoint.",
        "A rectangular yard measures 30 ft by 50 ft and contains a 10 ft by 12 ft garden. If a ball lands at a random point in the yard, what is the probability it lands in the garden?",
      ],
      isVerifiable: true,
      order: 36,
      nineWeeks: 4,
      requiresImage: true,
      imageType: 'geometric-figure',
    },
    {
      id: "geo.pr.2",
      tpiCode: "G.13A",
      name: "Permutations and Combinations",
      description:
        "Develop and use strategies based on the Fundamental Counting Principle, permutations, and combinations to count outcomes and solve contextual problems, distinguishing situations where order matters from situations where it does not.",
      gradeLevel: 10,
      strand: "Probability",
      difficulty: 2,
      prerequisites: [],
      sampleProblems: [
        "How many different 4-letter arrangements can be made using all the letters of the word MATH?",
        "A club of 10 students elects a president, a vice president, and a secretary. In how many ways can the three offices be filled?",
        "How many different 3-topping pizzas can be made from 8 available toppings?",
      ],
      isVerifiable: true,
      order: 37,
      nineWeeks: 4,
    },
    {
      id: "geo.pr.3",
      tpiCode: "G.13C/G.13D/G.13E",
      name: "Independent, Dependent, and Conditional Probability",
      description:
        "Identify whether two events are independent and compute the probability of both events occurring, with or without replacement. Apply conditional probability and independence to contextual problems, including problems based on two-way tables.",
      gradeLevel: 10,
      strand: "Probability",
      difficulty: 3,
      prerequisites: ["geo.pr.2"],
      sampleProblems: [
        "A bag holds 4 red and 6 blue marbles. Two marbles are drawn without replacement. Find the probability that both marbles are red.",
        "A coin is flipped and a number cube is rolled. Are the events 'heads' and 'rolling a 5' independent? Find the probability that both occur.",
        "In a class of 30 students, 18 play a sport, and 10 of those 18 also play an instrument. Find the probability that a randomly chosen student plays an instrument, given that the student plays a sport.",
      ],
      isVerifiable: true,
      order: 38,
      nineWeeks: 4,
    },
  ],
};
